- apps/docs/docs/learn/02-thinking-in-stylex.mdx
I could generally understand what was being written here, but the grammar was causing me to digest this a lot slower. Therefore, I made a PR to fix the spelling/grammar in various places.
If something doesn't make sense, I'll gladly clarify what I meant with the edit. Hope this helps any other future readers of the doc!
> Grammar and spelling fixes across the doc

- .github/CONTRIBUTING.md
- .gitignore
- .prettierignore
- apps/docs/README.md
- apps/docs/components/YouTube.js
- apps/docs/docs/api/configuration/babel-plugin.mdx
- apps/docs/docs/learn/02-thinking-in-stylex.mdx
- apps/docs/package.json
- apps/nextjs-example/app/page.tsx
- apps/nextjs-example/typetests/test3.tsx
- apps/rollup-example/index.js
- package-lock.json
- package.json
* Removes misleading information from the docs workspace README.
* Ensures the packages are automatically built after `npm install`
> Update setup instructions

- apps/docs/docs/learn/03-installation.mdx
- apps/webpack-example/webpack.config.js
In webpack config file [contenthash] has been added to the css file name to implement cache-busting.
Fixes #105 
> feat: Cache fix and docs updated

- apps/docs/docs/api/configuration/eslint-plugin.mdx
fixed typo error in the eslint-plugin api refrence page
Fixes # (issue) #159 
> fixed typo in the eslint-plugin api refrence page

- packages/rollup-plugin/README.md
Added documentation for installation process in README file of @stylex/rollup-plugin.
Fixes #164 
> docs: update readme for rollup plugin

- apps/docs/docs/learn/05-theming/02-using-variables.mdx
> docs: missing word

- packages/shared/src/types/index.js
Is there a word I don't know that says "creat"? If it's "create", there's room for confusion for juniors like me.
> fix: typo in comment

- apps/docs/package.json
- apps/docs/src/theme/Footer/index.js
- package-lock.json
Added vercel Analytics for the docs website.
> Chore: Add analytics

- apps/nextjs-example/typetests/theming1.tsx
- packages/stylex/src/StyleXTypes.d.ts
- packages/stylex/src/StyleXTypes.js
- packages/stylex/src/stylex.js
- packages/stylex/type-tests/theming1.js.flow
Adds a test to verify the types for Themes.
Fixes #176 
Fixes #208 
Fixes #188
> Fix: Connect theme types to VarGroup type in TS

- apps/docs/docs/api/types/StaticStyles.mdx
- apps/docs/docs/api/types/StyleXStyles.mdx
- apps/docs/docs/learn/02-thinking-in-stylex.mdx
- apps/docs/docs/learn/03-installation.mdx
- apps/docs/docs/learn/04-styling-ui/01-defining-styles.mdx
- apps/docs/docs/learn/04-styling-ui/02-using-styles.mdx
- apps/docs/docs/learn/05-theming/03-creating-themes.mdx
- apps/docs/docs/learn/07-acknowledgements.mdx
- apps/docs/docs/learn/index.mdx
Small fixes and improvements in the documentation.
> Docs: Small editing pass

- .github/workflows/tests.yml
This PR is a follow up on PR #260. I just realized that I forgot to update an action there. Sorry for the additional work.
> Bump checkout workflow to latest version v4

- apps/webpack-example/package.json
Just fixing a typo in the package.json
> fix typos in package.json

- packages/eslint-plugin/__tests__/stylex-valid-styles-test.js
- packages/eslint-plugin/src/stylex-valid-styles.js
Adds some missing properties to the ESLint rule.
Fixes #266 and #135
> Chore: Add missing properties to ESLint rule

- packages/stylex/.babelrc.js
- packages/stylex/package.json
This PR modifies the `build` script of `stylex` and adds `ECMAScript` module support for the package.
Fixes #205 
> feat: add `esm` bundle to `@stylexjs/stylex`

- README.md
- apps/nextjs-example/app/globalTokens.stylex.ts
- apps/nextjs-example/app/page.tsx
- packages/stylex/README.md
`import stylex from ...` -> `import * as stylex from ...`
> Fix stylex imports in docs

- packages/eslint-plugin/src/stylex-valid-styles.js
- packages/stylex/src/StyleXCSSTypes.js
Fixes #385 
Adds missing possible values for align-items, justify-items etc.
> fix: Add missing values for align/justify content/items

- apps/docs/docs/learn/03-installation.mdx
- packages/esbuild-plugin/README.md
Fixes the highlighting and formatting issue in the `esbuild-plugin` `README` file, as well as in the documentation example code snippet.
Fixes #407 
> chore: fix `esbuild-plugin` `README` nits

- apps/docs/docs/learn/03-installation.mdx
- packages/eslint-plugin/README.md
This PR updates the ESLint plugin README and simplifies its documentation, as discussed in #411. Fixes #411.
> doc: update the ESLint plugin README and documentation

- apps/docs/docs/learn/03-installation.mdx
Just a small update to fix the import in the esbuild plugin example
> docs: fix import in esbuild plugin example

- apps/docs/docs/api/configuration/dev-runtime.mdx
> fix: double insert key in line

- packages/shared/__tests__/convert-to-className-test.js
- packages/shared/src/utils/normalizers/zero-dimensions.js
Bug fix  🐛 🔧 
Fixes #498 #478 
Added a test in `convert-to-className-test.js`
> fix: 0 value handling for fraction and percentage

- README.md
> doc: Update README.md to include CLI in "packages" section

- apps/docs/docs/learn/05-theming/04-variable-types.mdx
update documentation code for creating theme from type defined variables
correcting the documentation
Please include relevant motivation and context
NA
current code
> Docs: Update 04-variable-types.mdx

- apps/docs/docs/learn/07-ecosystem.mdx
Add more links to the Ecosystem page.
> docs: Add community webpack and SWC plugins

- packages/esbuild-plugin/README.md
- packages/rollup-plugin/README.md
- packages/webpack-plugin/README.md
Changed README.md files for plugins to incorporate plugin specific options.
Fixes https://github.com/facebook/stylex/issues/629
> add: documentation for plugin specific options

- packages/shared/src/preprocess-rules/flatten-raw-style-obj.js
- packages/shared/src/transform-value.js
Don't add `px` to numbers used for `grid` properties.
> fix: Add more unitless properties

- packages/eslint-plugin/__tests__/stylex-valid-styles-test.js
- packages/eslint-plugin/src/stylex-valid-styles.js
> Fix nested usage of `@starting-style`

- apps/docs/static/robots.txt
Just adds a robots.txt file for algolia verification
> chore: add algolia search verification

- apps/cli-example/package.json
- apps/docs/blog/2024-06-28-Release-v0.8.0.mdx
- apps/docs/package.json
- apps/rollup-example/package.json
- apps/webpack-example/package.json
- package-lock.json
- package.json
- packages/babel-plugin/package.json
- packages/cli/package.json
- packages/dev-runtime/package.json
- packages/esbuild-plugin/package.json
- packages/eslint-plugin/package.json
- packages/nextjs-plugin/package.json
- packages/open-props/package.json
- packages/rollup-plugin/package.json
- packages/scripts/package.json
- packages/shared/package.json
- packages/stylex/package.json
- packages/webpack-plugin/package.json
New `0.8.0` release.
Release notes included.
> release: v0.8.0

- packages/babel-plugin/__tests__/stylex-transform-call-test.js
- packages/babel-plugin/__tests__/stylex-transform-stylex-attrs-test.js
- packages/babel-plugin/__tests__/stylex-transform-stylex-props-test.js
- packages/babel-plugin/src/utils/state-manager.js
- packages/esbuild-plugin/__tests__/__snapshots__/index-test.js.snap
- packages/rollup-plugin/__tests__/index-test.js
- packages/shared/__tests__/convert-to-className-test.js
- packages/shared/__tests__/flatten-raw-style-objects/legacy-shorthand-expansion-test.js
- packages/shared/__tests__/gen-css-test.js
- packages/shared/src/common-types.js
- packages/shared/src/convert-to-className.js
- packages/shared/src/utils/default-options.js
- packages/webpack-plugin/__tests__/index-test.js
Simple change to prefix dev classnames with the property name for debugging purposes. 
See discussion: https://github.com/facebook/stylex/issues/739
Added tests to ensure prefixing for dev mode and previous behaviour for production modes.
> feat: Prefix className with propName in development

- packages/babel-plugin/src/utils/state-manager.js
> fix: additional handling of relative path from esm-resolve

- packages/eslint-plugin/__tests__/stylex-valid-styles-test.js
- packages/eslint-plugin/src/stylex-valid-styles.js
- packages/stylex/src/StyleXCSSTypes.js
https://github.com/facebook/stylex/issues/135#issuecomment-2430087345
Ref:
https://developer.mozilla.org/en-US/docs/Web/CSS/interpolate-size
> Interpolate size

- apps/docs/docs/learn/06-recipes/01-context-driven-styles.mdx
- apps/docs/docs/learn/06-recipes/02-variants.mdx
- apps/docs/docs/learn/06-recipes/03-descendant styles.mdx
Iterate on the recipes section.
> docs: improve the recipes section further

- apps/docs/docs/learn/06-recipes/03-descendant styles.mdx
> Update 03-descendant styles.mdx

- apps/cli-example/package.json
- apps/docs/blog/2025-01-17-Release-v0.10.1.mdx
- apps/docs/package.json
- apps/nextjs-example/package.json
- apps/rollup-example/package.json
- apps/webpack-example/package.json
- package-lock.json
- package.json
- packages/babel-plugin/package.json
- packages/cli/package.json
- packages/dev-runtime/package.json
- packages/esbuild-plugin/package.json
- packages/eslint-plugin/package.json
- packages/nextjs-plugin/package.json
- packages/open-props/package.json
- packages/postcss-plugin/package.json
- packages/rollup-plugin/package.json
- packages/scripts/package.json
- packages/shared/package.json
- packages/stylex/package.json
- packages/webpack-plugin/package.json
Patch release with recent fixes.
> release: v0.10.1

- packages/cli/__tests__/compile-stylex-folder-test.js
- packages/cli/src/cache.js
- packages/cli/src/transform.js
Cherry picking https://github.com/facebook/stylex/pull/862 for version history
> fix: add cache invalidation on config change

- packages/cli/__tests__/compile-stylex-folder-test.js
- packages/cli/src/cache.js
Updated `findProjectRoot` fx to support Deno projects by adding `deno.json` and `deno.jsonc` as valid extensions, falling back to `.git` files if neither `project.json` nor `deno.json` are found.
Added a suite of tests for different root paths
> feat: add cli cache root detection for deno apps

- packages/cli/src/transform.js
Left a console log in transform.js
> chore: remove debug log in cache transform

- .flowconfig
- packages/babel-plugin/src/index.js
- packages/babel-plugin/src/utils/state-manager.js
- packages/cli/src/config.js
- packages/cli/src/index.js
- packages/cli/src/plugins.js
- packages/cli/src/transform.js
This reverts commit b58b29edb29a28db91cd2ee322c80cda4696c5bd.
Suspect this commit of causing CI failures internally.
> Revert "fix: cli should rewrite the aliases (#847)"

- .flowconfig
- packages/babel-plugin/src/index.js
- packages/babel-plugin/src/utils/state-manager.js
- packages/cli/src/config.js
- packages/cli/src/index.js
- packages/cli/src/plugins.js
- packages/cli/src/transform.js
This reverts commit ef75f1ee8a0493833c6bf5986710936b40c913a0.
Issue is actually in bundle script not detecting new files in https://github.com/facebook/stylex/pull/867
CI still failing
guess and check.........
> Revert "Revert "fix: cli should rewrite the aliases (#847)""

- packages/babel-plugin/src/utils/__tests__/state-manager.test.js
- packages/babel-plugin/src/utils/state-manager.js
- packages/babel-plugin/src/visitors/stylex-create/index.js
- packages/shared/__tests__/convert-to-className-test.js
More flags for rolling out newer debugging features internally.
> Add enableDevClassNames and enableDebugDataProp flags

- apps/cli-example/package.json
- apps/docs/package.json
- apps/esbuild-example/package.json
- apps/nextjs-example/package.json
- apps/rollup-example/package.json
- apps/webpack-example/package.json
- package-lock.json
- package.json
- packages/scripts/README.md
- packages/scripts/create-release.js
- packages/scripts/package.json
Adds a node script to automate the release and publish steps.
Example of how to run it:
```shell
npm run release
-w @stylexjs/scripts --
--pkg-version 0.10.2
--commit
--publish --otp 123456
```
Example result:
https://github.com/facebook/stylex/commit/99eae3e47f3a3abb5275cf677b04f4b52abc855a
Example of the other commands it runs for the git-commit and npm-publish step
> Automate release process

- apps/cli-example/package.json
- apps/docs/package.json
- apps/nextjs-example/package.json
- apps/rollup-example/package.json
- apps/webpack-example/package.json
- package-lock.json
- package.json
- packages/babel-plugin/package.json
- packages/cli/package.json
- packages/dev-runtime/package.json
- packages/esbuild-plugin/package.json
- packages/eslint-plugin/package.json
- packages/nextjs-plugin/package.json
- packages/open-props/package.json
- packages/postcss-plugin/package.json
- packages/rollup-plugin/package.json
- packages/scripts/package.json
- packages/shared/package.json
- packages/stylex/package.json
- packages/webpack-plugin/package.json
Release with new:
- Improved runtime debugging with sourceMap data
- CLI cache improvements: cache invalidation on config updates, relative filepath, deno app support
- Exported return types for 'stylex.types.*' fx
- ESLint valid-styles border autofixes
release notes: https://github.com/facebook/stylex/pull/909
> release: v0.11.0

- apps/docs/package.json
> Fix 'docs' stylesheet build

- vercel.json
Move Vercel configuration to the `vercel.json` instead of the Vercel UI.
> chore: Add more vercel config to the json file

- examples/example-cli/README.md
- examples/example-esbuild/README.md
- examples/example-nextjs/README.md
- examples/example-rollup/README.md
- examples/example-storybook/README.md
- examples/example-vite/README.md
- examples/example-webpack/README.md
Adds placeholder directories and READMEs for Vite and Storybook examples.
> Add more example app placeholders

- packages/style-value-parser/README.md
Adds README.md. First of a series of improvements to the style-value-parser we've been working on.
> docs: add readme for style-value-parser

- packages/babel-plugin/__tests__/transform-define-vars-test.js
* Use OSS defaults in tests.
* Reorganize tests.
* Simplify fixtures to focus on subject of test.
* Snapshot metadata.
> [babel-plugin] Refactor defineVars unit tests

- packages/babel-plugin/__tests__/transform-keyframes-test.js
> [babel-plugin] Refactor transform-keyframes-test

- packages/docs/docs/learn/03-installation.mdx
Just fixes some quotes in the docs for consistency.
This is just #900 since that PR has been sitting abandoned for a while now.
> docs: small quote formatting fix

- CHANGELOG.md
- packages/docs/blog/2025-04-10-Release-v0.12.0.mdx
> docs: release notes for v0.12.0

- examples/example-cli/package.json
- examples/example-esbuild/package.json
- examples/example-nextjs/package.json
- examples/example-rollup/package.json
- examples/example-webpack/package.json
- package-lock.json
- packages/babel-plugin/package.json
- packages/benchmarks/package.json
- packages/cli/package.json
- packages/docs/package.json
- packages/eslint-plugin/package.json
- packages/postcss-plugin/package.json
- packages/rollup-plugin/package.json
- packages/scripts/package.json
- packages/shared/package.json
- packages/style-value-parser/package.json
- packages/stylex/package.json
Changelog is getting pretty long...
```
$ npm run release -- -v 0.11.2
```
notes here: https://github.com/facebook/stylex/pull/988
> release: v0.12.0

- packages/docs/docs/learn/08-acknowledgements.mdx
> [docs] add Vincent Riemer to team

- packages/@stylexjs/babel-plugin/src/visitors/stylex-define-consts.js
- packages/docs/docs/api/index.mdx
- packages/docs/docs/api/javascript/defineConsts.mdx
- packages/docs/docs/api/javascript/defineVars.mdx
- packages/docs/docs/api/javascript/firstThatWorks.mdx
- packages/docs/docs/api/javascript/keyframes.mdx
- packages/docs/docs/api/javascript/props.mdx
- packages/docs/docs/api/javascript/types.mdx
Will wait until the rest of items in https://github.com/facebook/stylex/issues/1037 to merge
> [docs] api notes for defineConsts

- .eslintrc.js
- .prettierignore
- package-lock.json
- package.json
- packages/@stylexjs/stylex/flow-tests/theming1.js.flow
- packages/@stylexjs/stylex/src/types/StyleXTypes.d.ts
- packages/typescript-tests/package.json
- packages/typescript-tests/src/exports.ts
- packages/typescript-tests/src/styles.ts
- packages/typescript-tests/src/themes.ts
- packages/typescript-tests/tsconfig.json
As discussed in a few PRs related to TypeScript lately - I've made some setup for testing TypeScript types and added some initial test cases. I've added it as a separate package (as discussed here https://github.com/facebook/stylex/pull/1111) so it can properly work with codegen types and validate whether it behaves properly when it doesn't have access to some internal types.
Initial test cases:
- `exports.ts` - verifies whether everything works with TS declaration enabled, so that everything can be properly exported without errors, protects from issues such as https://github.com/facebook/stylex/issues/1070 and https://github.com/facebook/stylex/issues/857
- `styles.styles.ts` - verifies whether styles can be created and later used with stuff like `stylex.StyleXStyles` or …
> test: add TypeScript tests

- packages/@stylexjs/eslint-plugin/src/stylex-valid-styles.js
Simple dedupe of duplicated lint rules 
```
mellyeliu@mellyeliu-mbp eslint-plugin % npx jest stylex-valid-styles-test
Test Suites: 1 passed, 1 total
Tests:       103 passed, 103 total
Snapshots:   0 total
Time:        1.635 s, estimated 2 s
Ran all test suites matching stylex-valid-styles-test.
```
> [eslint-plugin] deduplicate property union rules

- packages/docs/docs/api/javascript/defineVars.mdx
- packages/docs/docs/learn/05-theming/01-defining-variables.mdx
> [docs] Documentation for creating CSS vars with stable names

- CHANGELOG.md
- examples/example-cli/package.json
- examples/example-esbuild/package.json
- examples/example-nextjs/package.json
- examples/example-rollup/package.json
- examples/example-webpack/package.json
- package-lock.json
- packages/@stylexjs/babel-plugin/package.json
- packages/@stylexjs/cli/package.json
- packages/@stylexjs/eslint-plugin/package.json
- packages/@stylexjs/postcss-plugin/package.json
- packages/@stylexjs/rollup-plugin/package.json
- packages/@stylexjs/stylex/package.json
- packages/benchmarks/package.json
- packages/docs/package.json
- packages/scripts/package.json
- packages/style-value-parser/package.json
- packages/typescript-tests/package.json
patch release for dynamic styles fix (https://github.com/facebook/stylex/pull/1153) + changelog
will wait until enforce media query ordering work is complete to put up 0.15:
- https://github.com/facebook/stylex/pull/1147
- and height based simplification i must add... 
using notes from https://github.com/facebook/stylex/pull/1123
> [release] v0.14.3

- .github/CODEOWNERS
adding Ezz to CODEOWNERS for faster review + validation work
> [config] add Ezz to CODEOWNERS

- packages/docs/blog/2025-07-31-Release-v0.15.0.mdx
- packages/docs/blog/authors.yml
> [docs] release notes for v0.15.0

- examples/example-cli/package.json
- examples/example-esbuild/package.json
- examples/example-nextjs/package.json
- examples/example-rollup/package.json
- examples/example-webpack/package.json
- package-lock.json
- packages/@stylexjs/babel-plugin/package.json
- packages/@stylexjs/cli/package.json
- packages/@stylexjs/eslint-plugin/package.json
- packages/@stylexjs/postcss-plugin/package.json
- packages/@stylexjs/rollup-plugin/package.json
- packages/@stylexjs/stylex/package.json
- packages/benchmarks/package.json
- packages/docs/package.json
- packages/scripts/package.json
- packages/style-value-parser/package.json
- packages/typescript-tests/package.json
Release notes for changelog: https://github.com/facebook/stylex/pull/1234
> [release] v0.16.0
