facebook/stylex

apps/docs/docs/api/configuration/babel-plugin.mdx
A period was missing at the end of a sentence. (babel plugin)
=> Fix documentation typo

.github/workflows/typos.yml, apps/docs/blog/2023-12-05-introducing-stylex.md, apps/docs/docs/api/configuration/eslint-plugin.mdx, apps/docs/docs/api/types/StyleXStylesWithout.mdx, apps/docs/docs/learn/02-thinking-in-stylex.mdx, apps/docs/docs/learn/06-static-types.mdx, apps/nextjs-example/app/globalTokens.stylex.ts, packages/babel-plugin/README.md, packages/babel-plugin/__tests__/stylex-transform-call-test.js, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/__tests__/stylex-transform-create-vars-test.js, packages/babel-plugin/__tests__/stylex-transform-override-vars-test.js, packages/babel-plugin/__tests__/stylex-transform-stylex-props-test.js, packages/babel-plugin/__tests__/stylex-transform-value-normalize-test.js, packages/babel-plugin/src/index.js, packages/babel-plugin/src/utils/dev-classname.js, packages/dev-runtime/__tests__/stylex-transform-create-test.js, packages/eslint-plugin/src/utils/getDistance.js, packages/shared/README.md, packages/shared/__tests__/stylex-create-test.js, packages/shared/src/messages.js, packages/shared/src/preprocess-rules/basic-validation.js, packages/shared/src/utils/normalizers/whitespace.js, packages/shared/src/utils/split-css-value.js, packages/stylex/README.md, typos.toml
This pull request introduces a significant enhancement to the project's code quality by implementing the `typos` tool. It serves to identify and correct spelling errors throughout the codebase. Additionally, a `typos CI workflow` has been configured to ensure ongoing spelling accuracy in future contributions.
1. **Spelling Corrections**: All identified spelling mistakes have been corrected across various files in the project, improving the readability and professionalism of the code.
2. **Typos CI Workflow**: The integration of `typos` into our continuous integration workflow adds an automatic spell check step. This ensures that new commits adhere to the same level of spelling accuracy, maintaining the overall quality of our code.
3. **Documentation Update**: Where applicable, …
=> Implement Typos CI Workflow and Correct Spelling Errors Across the Project

apps/docs/docs/learn/04-styling-ui/01-defining-styles.mdx, apps/docs/docs/learn/06-static-types.mdx, apps/docs/docs/learn/index.mdx
fixed typo from (uses cases) to (use cases)
=> docs typo fixed

package-lock.json, packages/rollup-plugin/package.json
`@stylexjs/rollup-plugin` loose necessary dependencies, So this pull request add them.
=> fix: rollup plugin add necessary deps

apps/docs/docs/learn/05-theming/03-creating-themes.mdx
=> Fix Typo in Themes Docs

apps/docs/src/theme/MDXComponents/Details.js, apps/docs/src/theme/MDXComponents/DetailsTokens.stylex.js
It was a little annoying that the collapsible items on the current docs have a smaller hitbox than the entire size/area of the collapsible item. I saw that @nmn fixed the undesired click behavior on the same component [0e3cfb4](https://github.com/facebook/stylex/commit/0e3cfb4fcfd56a23a5af1a2dd9a561fa10f53eba) here. Just wanted to make the component more convenient and intuitive to use for future users. 
None
Before/After behavior. Tested with keyboard actions. ARIA labels not provided.
https://github.com/facebook/stylex/assets/15972898/38204d9f-7725-4c8f-937c-db28f4bac7d1
=> docs: Enable click event on full collapsible area

apps/docs/.stylelintrc.js, apps/docs/README.md, apps/docs/package.json
I noticed that the project was mainly using npm, however, the docs app (website) was using yarn. I have edited the package.json to migrate yarn commands to npm and updated README to reflect the changes
None
- I would propose migrating to [pnpm](https://pnpm.io/pnpm-vs-npm)
- Also added documentation about building stylex packages to README
- **Important!**: It seems that stylelint fails due to a missing package `stylelint-copyright` and `lint & ci` commands seems to fail. Was not sure if this was expected behavior and if the linter is only ran on ci.
- Testing was done to make sure current behavior does not change
- Added `**/build/**` to stylelint (was not sure if this is a desired behavior)
=> docs: Migrate docs pm to npm from yarn

apps/docs/docs/learn/index.mdx
There is a typo on word `Javascript`. It should be `JavaScript`.
=> docs: fix typo in learn section

apps/docs/docs/learn/05-theming/02-using-variables.mdx
Documentation Enhancement: Complete Variable Examples with Spacing Definition
The code example in _components/MyComponent.js_ references `import {colors, spacing} from '../tokens.styles';` , which implies that both colors and spacing are defined within _tokens.styles.js_ . 
Without the spacing variable defined in _tokens.stylex.js_, this could lead to confusion for users trying to understand the complete implementation of StyleX variables. 
By including the spacing definition, it provides a more comprehensive example and aligns the documentation with the code, enhancing overall clarity and usability.
=> Document Update: Add Spacing Definition to tokens.stylex.js

apps/docs/docs/learn/06-static-types.mdx
AFAIK, `React.MixedElement` is not a valid type in Typescript
=> Remove `React.MixedElement` from the typescript example

packages/stylex/src/StyleXTypes.d.ts
This PR solves the problem described within #68.
Can you please check? @nmn
=> fix: TypeScript autocomplete issue #68

apps/docs/components/CtaButton.js, apps/docs/src/css/custom.css
Addresses the issue #76 
Changed contrast color for both CTA and search placeholder texts.
| Before | After |
| ------ | ----- |
| ![image](https://github.com/facebook/stylex/assets/45975811/0afcb27a-1cdc-47e6-8776-8737289be438) | ![image](https://github.com/facebook/stylex/assets/45975811/98e571a0-4b69-4570-b411-09777654db2f) |
Passes the lighthouse test:
=> docs: increase contrast in home CTA and search

packages/babel-plugin/src/visitors/stylex-create/index.js
In `validateStyleXCreate`, we have checked whether the first argument is `ObjectExpression` or not. It seems that we don't need to check it again. Furthermore, the error message should be `messages.NON_OBJECT_FOR_STYLEX_CALL`
=> refactor(babel-plugin): remove unnecessary check

apps/nextjs-example/next.config.js, packages/nextjs-plugin/src/custom-webpack-plugin.js, packages/nextjs-plugin/src/index.js, packages/rollup-plugin/__tests__/index-test.js, packages/rollup-plugin/src/index.js, packages/webpack-plugin/src/index.js
The function to generate CSS from extracted styles can use CSS `@layer` or polyfill using `:not(#\#)`. This PR adds an option to all existing bundler plugins to control this behaviour.
=> Enhancement: Add option to use CSS layers to all bundler plugins

apps/nextjs-example/app/page.tsx
Refactored the Card Component Rendering in page.tsx
Issue: The Card component was instantiated multiple times to render multiple content.
Solution: Implemented a more favorable approach by creating a 'cards' array of objects and utilizing the map function to render each Card component. This not only reduces code redundancy but also improves the maintainability and readability.
---
I tried earlier but had some issues and fixed that, but now there's one issue that persists and am not sure if this will work. Am sorry, didn't mean to do it twice. I've mentioned the issue in #93
=> refactor: nextjs-example page.tsx code refactored for better readability

apps/docs/package.json, package-lock.json, package.json, packages/scripts/gen-types.js
Resolves #78 
There are three solve issues fixed in this PR:
1. `rm -rf` doesn't exist on windows. Replaced with `rimraf`.
2. `NODE_ENV=...` doesn't exist on windows. Replaces with `cross-env NODE_ENV=...`
3. Windows will use `\r\n` for line endings which broke `gen-types` script. Updated the script to find and replace all `\r\n` with `\n` first.
=> Fix: Builds on Windows

apps/nextjs-example/app/globals.css
The nextJS example didn't have margins or paddings because the reset styles overriding all StyleX styles. (because of `@CSS layers`).
Fixed this by putting the reset styles in a CSS Layer themselves.
=> Fix: CSS layer order in Next.js app

packages/stylex/src/StyleXCSSTypes.js
This PR will adds `string and number` type in `fontWeight` types in `StyleXCSSTypes.js`  
Fixes #124 
Tested it
=> fix : add types to fontWeight

packages/babel-plugin/__tests__/stylex-transform-call-test.js, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/shared/__tests__/stylex-create-test.js, packages/shared/src/preprocess-rules/application-order.js
The `application-order` style mergin strategy was accidentally not generating styles for `border-left` and `border-inline-start`. This PR fixes that.
#127 
Added a unit test for this
=> Fix: border-left not being rendered

packages/babel-plugin/__tests__/stylex-transform-call-test.js, packages/babel-plugin/src/utils/state-manager.js, packages/babel-plugin/src/visitors/imports.js
By default you import stylex from the `@stylexjs/stylex` package and the compiler detects and compiles that. It has also been possible to set up custom import paths for custom aliases. However, so far it was expected that you'd still use `import * as <name>` from a custom source.
This PR adds the ability to mark `stylex` to be a named export from a custom path. This lets enables the following pattern:
```ts
import {html, css} from 'browser';
const styles = css.create({
foo: {...}
});
css.props(styles.foo);
```
This will enable larger UI frameworks to incorporate StyleX within their own API.
Added a couple of tests which are passes as expected.
=> Enhancement: Add option to process arbitrary named exports

apps/nextjs-example/package.json
I changed the package.json of the Next.js example to delete the .next directory before building the Next application.
Fixes #109 (point 3 of the overview list)
I didn't remove the predev script because it allows users to run the dev server with cleanup without building first. But I can remove it if desired.
Based on the cleanup script, this might work for this example, but might lead to longer build times if you start from scratch every time?
Shouldn't fail any tests since I only changed the package.json and the Next.js app build works accordingly.
=> Chore: Added cleanup script for Next.js building

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-valid-styles.js
I have fixed to report when a value other than an `ObjectExpression` is specified as an argument for `stylex.create`.
=> fix: strict report for stylex.create argument as object expression

apps/docs/docs/learn/05-theming/03-creating-themes.mdx
Fixed Typo in the documentation.
Please include relevant motivation and context
1. It's generally good practice to include a space before the curly braces in the import statement for better readability.
2. descendants spelling was incorrect.
3. Replaced 'on' with 'to' which is a minor grammatical error.
1. It's generally good practice to include a space before the curly braces in the import statement for better readability.
2. descendants spelling was incorrect.
3. Replaced on with to which is a minor grammatical error
=> Fixed Typo

apps/docs/src/css/custom.css
`docusaurus` dark theme variables were not applied , so instead we can use that dark theme related variables in custom css (not more than 6 variables and it solve the problem without needing to specify properties for the panel and search buttons.
Fixes #149 
=> fix : dark theme inconsistency

apps/docs/docs/learn/04-styling-ui/02-using-styles.mdx
1. - What: Fixed a little typo in [Merging styles](https://stylexjs.com/docs/learn/styling-ui/using-styles/#merging-styles) section
- Why: Typos can be distracting and lead to confusion, this change will help avoiding it.
2. - What: Clarified that props function also ignores empty objects
- Why: It's important to understand how the props function handles the logic for devs who will use this function throughout their apps and this change will ensure devs are aware of this scenario.
=> Fixed typo in 02-using-styles.mdx page

apps/docs/docs/api/javascript/props.mdx, apps/docs/docs/learn/06-static-types.mdx
In this commit, I addressed a typographical error found on the props.mdx page, ensuring accuracy and clarity in the documentation.
Fix for the issue of not copying to the clipboard mentioned in issue #121 , has been proposed with this pull request.
Additionally, I added the number "16" to a comment in the 06-static-types.mdx file to provide context and enhance the comprehensibility of the code. This change aims to improve the overall quality and understanding of the static types section.
These modifications contribute to a more polished and user-friendly documentation experience.
- The typo fix in the props.mdx page is crucial for maintaining precision in the documentation, particularly in conveying information about component properties.
- The Copy to ClipBoard option not working …
=> docs: Fixing a typo on props.mdx page, fixed the issue of not copying to clipboard and added 16 to the comment on 06-static-types.mdx

apps/docs/components/CtaButton.js, apps/docs/src/pages/index.js
FIX: CTA section's responsive issue fixed
When screen size is around 370-380px the CTA section touches the edge which is not looks good (Please check the attached screenshot)
- There was several options to fix it. I just reduced the padding-x of those button when screen size is less then 390px
Hope you are going great. 
Please check my changes and if you have suggestions or need any modification please let me know. 
Thank you for your time and consideration!
=> fix: cta section responsive issue

packages/nextjs-plugin/README.md, packages/webpack-plugin/README.md
Added documentation for installation process in `README` file of `@stylexjs/nextjs-plugin` and `@stylexjs/webpack-plugin`
Fixes #164 
=> docs: update readme for nextjs and webpack plugin

apps/docs/docs/learn/03-installation.mdx
Considering the significance of variables in StyleX, I suggest adding the `treeshakeCompensation` property to the installation steps for Next.js. Without this property, variables are removed during compilation as they are considered dead code. This can lead to confusion and difficulty for developers in setting up a project effortlessly.
=> docs: add treeshakeCompensation option to Next.js installation guide

package-lock.json, packages/babel-plugin/__tests__/evaluation/stylex-import-evaluation-test.js, packages/babel-plugin/__tests__/stylex-transform-call-test.js, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/__tests__/stylex-transform-create-vars-test.js, packages/babel-plugin/__tests__/stylex-transform-import-test.js, packages/babel-plugin/__tests__/stylex-transform-keyframes-test.js, packages/babel-plugin/__tests__/stylex-transform-legacy-shorthands-test.js, packages/babel-plugin/__tests__/stylex-transform-logical-properties-test.js, packages/babel-plugin/__tests__/stylex-transform-logical-values-test.js, packages/babel-plugin/__tests__/stylex-transform-override-vars-test.js, packages/babel-plugin/__tests__/stylex-transform-stylex-props-test.js, packages/babel-plugin/__tests__/stylex-transform-value-normalize-test.js, packages/babel-plugin/__tests__/stylex-transform-variable-removal-test.js, packages/babel-plugin/flow_modules/@babel/helper-module-imports/index.js.flow, packages/babel-plugin/flow_modules/@babel/traverse/index.js.flow, packages/babel-plugin/package.json, packages/babel-plugin/src/utils/state-manager.js, packages/babel-plugin/src/visitors/stylex-create-theme.js, packages/babel-plugin/src/visitors/stylex-create/index.js, packages/babel-plugin/src/visitors/stylex-define-vars.js, packages/babel-plugin/src/visitors/stylex-keyframes.js, packages/rollup-plugin/__tests__/index-test.js, packages/shared/src/common-types.js, packages/shared/src/utils/default-options.js, packages/stylex/__tests__/stylex-test.js, packages/stylex/src/stylex.js, packages/webpack-plugin/__tests__/index-test.js
The `inject` function has been removed from the main export of `@stylex/stylex`. Now the inject function can only be used by manually importing `@stylex/stylex/lib/stylex-inject`.
The Babel plugin has similarly been updated to import the `inject` function from the new location when `runtimeInjection` is turned on.
Also, `runtimeInjection` now accepts a string or `{from: string, as: string}` object to be able to override the `inject` function module location.
Tests have been updated to reflect the changes. The updated snapshots will show what has changed.
NOTE: The Webpack plugin is currently inlining the `stylex-inject` module in the generated code in the snapshot test. Trying to configure Webpack to not do that is causing strange errors.
=> Perf: Remove runtime injection from runtime

apps/docs/docs/learn/05-theming/03-creating-themes.mdx
Based on the example found on the [Using variables](https://github.com/facebook/stylex/blob/7ddea4976e6aecd9af56e37f758c65569e52505b/apps/docs/docs/learn/05-theming/02-using-variables.mdx#L60) page, I believe this other example is using an incorrect filename for the tokens import.
=> docs: fix import in creating themes example

packages/webpack-plugin/__tests__/index-test.js, packages/webpack-plugin/src/index.js
Webpack only supports token replacement for chunks and modules, not plain assets. Instead, teach the plugin to do token replacement the same way that webpack does it for supported types.
Fixes #105 
=> Support replacement tokens in the webpack filename

packages/babel-plugin/__tests__/stylex-transform-define-vars-test.js, packages/babel-plugin/__tests__/stylex-transform-override-vars-test.js, packages/babel-plugin/src/visitors/stylex-create-theme.js, packages/babel-plugin/src/visitors/stylex-define-vars.js, packages/dev-runtime/__tests__/stylex-transform-create-theme-test.js, packages/dev-runtime/__tests__/stylex-transform-define-vars-test.js, packages/dev-runtime/src/index.js, packages/open-props/__tests__/__snapshots__/open-props-compile-test.js.snap, packages/shared/__tests__/stylex-create-vars-test.js, packages/shared/__tests__/stylex-override-vars-test.js, packages/shared/src/stylex-create-theme.js, packages/shared/src/stylex-define-vars.js
When defining variables with `defineVars` and `createTheme`, the generated CSS was generated as a single string. When `@` rules were used this string contained multiple CSS rules.
In development, when `runtimeInjection` is `true`, this would try to insert the whole string with the browser's `insertRule` API. This would error.
This PR, breaks up the generated CSS into individual rules that can be injected separately at runtime (when in development)
**NOTE:** This is a fix for development workflows. Everything already worked for production builds.
#235 
Test snapshots have been updated and I have verified that everything looks right.
=> Fix: Insert individual rules for runtimeInjection

apps/docs/docs/learn/05-theming/01-defining-variables.mdx, apps/docs/docs/learn/05-theming/02-using-variables.mdx
- The code change in the commit involves the removal of some style variables from the colors object. The motivation behind this change is likely to simplify the codebase by removing unused or unnecessary style variables, which can contribute to cleaner and more maintainable code.
Fixes [#231](https://github.com/facebook/stylex/issues/231)
=> refactor: remove unused style variables 

apps/docs/docs/learn/index.mdx
For some reason or another (despite the fact "palegoldenrod" is a color) "lightred" does not appear to be a valid CSS color. 
https://www.w3.org/wiki/CSS/Properties/color/keywords
I was trying the intro and the background didn't change to light red.
Didn't make an issue.
No.
=> Update index.mdx to use valid css color

packages/babel-plugin/__tests__/stylex-validation-create-test.js, packages/babel-plugin/src/visitors/stylex-create/index.js, packages/babel-plugin/src/visitors/stylex-create/parse-stylex-create-arg.js, packages/eslint-plugin/src/stylex-valid-styles.js, packages/shared/src/messages.js
This PR improves the error messaging for `stylex.create` dynamic values. In particular, it throws a more verbose error when consumers attempt to set default parameters or don't use named parameters. Previously, in both cases it would just throw `NON_STATIC_VALUE` error. I also improved the error message in `eslint-plugin`.
Let me know if the error messages themselves can be improved.
Fixes #198 
=> feat: improve error messaging in `stylex.create`

.github/workflows/performance.yml, .github/workflows/tests.yml
This PR bumps GitHub workflow actions to their latest versions, thus avoiding deprecation warnings as seen [here](https://github.com/facebook/stylex/actions/runs/7320001293).
=> Bump GitHub workflow actions to latest versions

packages/babel-plugin/__tests__/stylex-transform-call-test.js, packages/babel-plugin/__tests__/stylex-transform-stylex-props-test.js, packages/babel-plugin/src/index.js, packages/babel-plugin/src/utils/state-manager.js, packages/babel-plugin/src/visitors/stylex-merge.js, packages/babel-plugin/src/visitors/stylex-props.js
At a high-level, the StyleX compiler works in the following steps:
1. All the function calls other than `stylex()` and `stylex.props()` are compiled down. `stylex.create` calls are replaced by object expressions that map keys to classNames.
2. We try to precompute `stylex()` and `stylex.props()` calls. Replacing them string constants if possible.
3. If all references to the compiled styles from step 1 are removed, we can remove the object entirely.
This PR improves the dead-code elimination from step 3. Now, when there are dynamic references that exist after compilation to style objects, only the style objects that are needed are kept, and other style rules within the same variable declaration can be removed.
TLDR; Extra sub-objects are removed from the compiled code.
A couple of …
=> feat: Remove style rules that are not needed

apps/nextjs-example/.babelrc.js, apps/nextjs-example/app/Card.tsx, apps/nextjs-example/app/Counter.tsx, apps/nextjs-example/app/page.tsx, apps/nextjs-example/next.config.js, packages/babel-plugin/src/index.js, packages/stylex/src/StyleXSheet.js, packages/webpack-plugin/__tests__/index-test.js
Update the logic for runtime injection to:
1. Log errors when encountered. Currently they're silently ignored
2. Insert styles defensively. Currently, one failure causes many further insertions to fail.
3. Use the `:not(#/#)` selector to bump specificity for consistency.
Also, updated the NextJS example to include a Counter which is a Client Component.
This should fix usage in NextJS `pages` directory.
=> Fix: Fix specificity of styles injected at runtime

apps/nextjs-example/app/Counter.tsx, packages/eslint-plugin/src/stylex-valid-styles.js, packages/eslint-plugin/src/utils/resolveKey.js
In some edge-cases constants used as media queries weren't handled correctly by the ESLint plugin. Fix that.
=> fix: ESLint - Resolve local constant used as keys

apps/docs/docs/api/javascript/createTheme.mdx, apps/docs/docs/api/javascript/defineVars.mdx
| Before | After |
| - | - |
| ![stylexjs com_docs_learn_styling-ui_defining-styles_](https://github.com/facebook/stylex/assets/76220140/cc612461-c45c-4ec5-9083-081e082b4c4f) | ![localhost_3000_docs_api_javascript_defineVars_](https://github.com/facebook/stylex/assets/76220140/bfafbaae-7aa9-46ea-b85b-53f636f28479) |
Having it as `export const colors` just makes it clear that it should be exported. As for the other changes, nitpicks.
=> Docs: Improve code examples

packages/babel-plugin/src/utils/state-manager.js
There is a bug right now where setting `runtimeInjection` to `false` doesn't actually work. This PR fixes that.
=> Fix: Respect runtimeInjection: false

apps/nextjs-example/app/globalTokens.stylex.ts, packages/babel-plugin/__tests__/stylex-transform-define-vars-test.js, packages/babel-plugin/__tests__/stylex-transform-override-vars-test.js, packages/babel-plugin/flow_modules/@babel/core/index.js.flow, packages/babel-plugin/src/utils/__tests__/state-manager.test.js, packages/babel-plugin/src/utils/state-manager.js, packages/babel-plugin/src/utils/validate.js
Improve the Babel plugin's `StateManager` to not use `$FlowFixMe` (`any`) and instead of validate the options passed in.
The code is very imperative at the moment and feels a bit hard to read and fragile. I'm looking into using a library like `zod` to clean this up.
=> Fix: Validate options passed into the Babel plugin

apps/docs/docs/api/javascript/createTheme.mdx, apps/docs/docs/api/javascript/defineVars.mdx, packages/babel-plugin/__tests__/stylex-validation-define-vars-test.js, packages/babel-plugin/src/visitors/stylex-define-vars.js
This PR fixes the bug, where consumers cannot create `keyframes` directly inside `defineVars`.
```
export const vars = stylex.defineVars({
fadeIn: stylex.keyframes({
'0%': { opacity: 0 },
'100%': { opacity: 1},
}),
});
```
Fixes #291 
=> fix: creating `keyframes` inside `defineVars`

README.md
Updated capitalisation in `README.md` file to match documentation website.
I was trying to reference this project and wanted to quickly understand how this project should be capitalised. From what I can tell it should be `StyleX` so I wanted to make that clear in the README file.
=> Update capitilisation of stylex to match documentation StyleX

packages/eslint-plugin/src/stylex-valid-styles.js
Fixes #320 
Adds support for missing pseudo elements to the ESLint plugin.
Also, improve the error message when an unknown pseudo element is used.
=> [ESLint] Add support for missing -webkit-scrollbar pseudo elements

apps/docs/docs/api/index.mdx, apps/docs/docs/api/javascript/attrs.mdx, apps/docs/docs/api/javascript/createTheme.mdx, apps/docs/docs/api/javascript/defineVars.mdx, apps/docs/docs/api/javascript/firstThatWorks.mdx, apps/docs/docs/api/javascript/keyframes.mdx, apps/docs/docs/learn/04-styling-ui/02-using-styles.mdx, packages/babel-plugin/__tests__/stylex-transform-stylex-attrs-test.js, packages/babel-plugin/src/index.js, packages/babel-plugin/src/utils/state-manager.js, packages/babel-plugin/src/visitors/imports.js, packages/babel-plugin/src/visitors/stylex-attrs.js, packages/stylex/src/stylex.js
For frameworks such as Solid, Qwik, Svelte, Vue, etc. that require a `class` instead of `className`, there is now a first-class API called `stylex.attrs` which can be used in place of `stylex.attrs`.
`stylex.attrs` returns an object with a `class` key instead of a `className` key and pre-converts the value of `style` to a string as not every framework accepts objects for inline styles.
In all other ways, `stylex.attrs` is identical to `stylex.props`. At runtime it uses `stylex.props` internally. At compile time, it benefits from the same optimisations as `stylex.props`.
@PatrickJS
=> feat: Add stylex.attrs for frameworks that expect 'class' over 'className'

.eslintrc.js, packages/stylex/.babelrc.js
Resolving an issue discovered in 0.5.0-beta.2 in the issue #47 discussion.
Sometimes, Vite breaks because ESM exports didn't have file extensions in the import statements.
=> fix: Add file extensions to ESM exports

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/rules/isAnimationName.js, packages/eslint-plugin/src/stylex-valid-styles.js
This PR fixes the issue, where `eslint` would show an error when using `keyframes` named import as `animationName` property value.
Fixes #322 
=> bug: check for `keyframes` imports in `animationName` eslint rule

packages/stylex/src/StyleXCSSTypes.js
This PR adds support for string values for `opacity`.
Fixes #356
=> fix: support string values for opacity

packages/eslint-plugin/src/stylex-valid-styles.js, packages/stylex/src/StyleXCSSTypes.js, packages/stylex/src/StyleXTypes.d.ts
Adds some missing CSS properties that were either missing in the type definitions or the ESLint rule.
Fixes #135
=> Fix: Add missing CSS properties to types and ESLint

apps/nextjs-example/tsconfig.json, flow-typed/npm/postcss-value-parser_vx.x.x.js, packages/babel-plugin/__tests__/stylex-transform-call-test.js, packages/open-props/__tests__/__snapshots__/open-props-compile-test.js.snap, packages/shared/src/utils/normalizers/whitespace.js, packages/shared/src/utils/normalizers/zero-dimensions.js
Fixes #351 
Possibly due to browser bugs, using a unit-less `0` within `max()` functions doesn't work within certain browsers. Also, within mathematical expressions spaces around units are often required.
This PR fixes both those issues.
NOTE: If the authored code uses a unit-less `0`, a unit will *not* be added.
=> fix: Keep units for 0 within functions

packages/esbuild-plugin/src/index.js
A very minor nit. I realized there was a useless comment left in the main file of the `esbuild-plugin` module. This PR removes it.
none
=> chore: remove useless comment

packages/babel-plugin/__tests__/evaluation/stylex-import-evaluation-test.js, packages/babel-plugin/__tests__/stylex-transform-call-test.js, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/__tests__/stylex-transform-define-vars-test.js, packages/babel-plugin/__tests__/stylex-transform-import-test.js, packages/babel-plugin/__tests__/stylex-transform-keyframes-test.js, packages/babel-plugin/__tests__/stylex-transform-legacy-shorthands-test.js, packages/babel-plugin/__tests__/stylex-transform-logical-properties-test.js, packages/babel-plugin/__tests__/stylex-transform-logical-values-test.js, packages/babel-plugin/__tests__/stylex-transform-override-vars-test.js, packages/babel-plugin/__tests__/stylex-transform-stylex-attrs-test.js, packages/babel-plugin/__tests__/stylex-transform-stylex-props-test.js, packages/babel-plugin/__tests__/stylex-transform-value-normalize-test.js, packages/babel-plugin/__tests__/stylex-transform-variable-removal-test.js, packages/babel-plugin/src/utils/state-manager.js
A previous change ensures that the `inject` function is imported and then aliased as a variable before being used.
This change is a workaround for the way Babel deals with ES6 imports.
Previously, this `inject` alias variable was inserted after the last import statement. However, this breaks in some edge-cases where import statements may exist *after* `inject` has already been used.
This PR changes the behaviour to add the variable alias immediately after the `inject` function is imported.
=> Fix: Ensure 'inject' variable is defined before use

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-valid-styles.js
Fixed the following cases casuing "Computed key cannot be resolved.eslint(@stylexjs/valid-styles)" lint error.
```ts
import stylex from'stylex';
import { componentVars } from './bug.stylex';
stylex.create({
host: {
[componentVars.color]: 'blue',
},
})
```
```ts
import stylex from'stylex';
import { tokens } from 'tokens.stylex';
stylex.create({
root: (position) => ({
[tokens.position]: `${position}px`,
})
})
```
Fixes #337
For dynamic styles (not `style.value.type === 'ObjectExpression'`) we are missing the check for stylex defined variables for object keys, resulting in the "cannot be resolved" error, the fix was to add an early check for the style key being a defined variable and returning early.
TBH I don't quite understand why the first case was broken as reported in #337, how is that …
=> fix: eslint allow using vars as key in dynamic styles

packages/eslint-plugin/__tests__/stylex-sort-keys-test.js, packages/eslint-plugin/src/stylex-sort-keys.js
Fix a bug where the `sort-keys` rule is giving errors for nested keys, comparing them to the parent keys.
Fixes #391 
I *think* the issue here is that, after adding the outer object to the stack, subsequent nested objects are never actually pushed onto this stack, resulting in a stack that maintains only a single layer.
=> fix: fix eslint sort-keys handling nested properties

packages/esbuild-plugin/README.md
Fixed wrong import location in esbuild plugin.
None
None
=> fix: Corrected wrong import location of esbuild plugin in README

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/rules/makeRangeRule.js, packages/eslint-plugin/src/stylex-valid-styles.js
This PR tells the ESLint plugin to allow  `fontWeight` to have any number between 1 and 1000 instead of some fixed ones like `100`, `200`... Fixes #419.
=> fix (ESLint Plugin): allow font weights between 1 and 1000

apps/nextjs-example/typetests/test1.tsx, packages/stylex/src/StyleXTypes.d.ts
The typescript type definitions for `StyleXStyles` and `StaticStyles` did not accept `undefined` but they did accept `null`. This was an oversight, and has been fixed in this PR.
Fixes #417 
A type test has been added to verify the fix.
=> Fix: Allow undefined within StyleXStyles and StaticStyles

apps/docs/docs/api/index.mdx, apps/docs/docs/api/types/Theme.mdx, apps/docs/docs/api/types/VarGroup.mdx
Document public types `VarGroup` and `Theme`. The writing could probably be better,
but sharing early for feedback.
Fixes #424
=> Docs: Document VarGroup and Theme types

packages/stylex/package.json
I was attempting to build on windows and was getting that `BABEL_ENV` wasn't found. Seems like adding `cross-env` like the other `NODE_ENV` in the repo uses fixes it.
=> Fix: stylex package build on windows

packages/shared/__tests__/convert-to-className-test.js, packages/shared/__tests__/stylex-first-that-works-test.js, packages/shared/src/convert-to-className.js, packages/shared/src/messages.js, packages/shared/src/stylex-first-that-works.js
This PR makes it possible to use `stylex.firstThatWorks` to also work
for fallback values for CSS variables.
Something like this should now work:
```tsx
margin: stylex.firstThatWorks(vars.foo, 200)
```
Fixes #432 
A unit test has been added for the new behaviour.
----
`stylex.firstThatWorks` is a lightweight transform that simply converts the arguments to an array reverses them. This transform is still unchanged. This is important so that we can convert numbers to the correct type of string.
But after the values are converted to `px` (or not), it now looks for variables within the array of values and compresses them to handle this case correctly.
It can handle `[...values, ...variables, ...values]`;
Non-contiguous variables are not allowed.
Therefore a complex value like this would work: …
=> feat: Handle variable fallbacks with firstThatWorks

apps/esbuild-example/scripts/build.mjs, apps/nextjs-example/.babelrc.js, apps/rollup-example/rollup.config.mjs, apps/webpack-example/webpack.config.js
I spent half a day trying to work out why my stylex variables were getting stripped out unless I had a `console.log` logging them. It turns out there's an option for the [babel plugin options](https://stylexjs.com/docs/api/configuration/babel-plugin/) of `treeshakeCompensation` which solved the issue.
It was not obvious to me that the object here was being passed to the babel plugin behind the scenes, which I only discovered by digging through the source code. Hopefully this comment helps others gain a better understanding of how the `stylexPlugin` works under the hood.
Documentation (comment) only change
=> Add babel plugin options comment to esbuild example

package-lock.json, packages/babel-plugin/src/utils/state-manager.js, packages/babel-plugin/src/visitors/stylex-create-theme.js, packages/babel-plugin/src/visitors/stylex-create/index.js, packages/babel-plugin/src/visitors/stylex-define-vars.js, packages/babel-plugin/src/visitors/stylex-keyframes.js, packages/open-props/__tests__/__snapshots__/open-props-compile-test.js.snap
Creates a new function to the `StateManager` to take all the injected styles and set the `metadata` and, if needed, insert the code for injecting those styles at runtime.
This makes the code DRY and unifies the style injection code.
This is also a prerequisite for using CSS data imports for styles.
=> chore: Unified function to inject styles

package-lock.json, packages/webpack-plugin/package.json
The webpack plugin should not have a dependency on webpack. Instead, it now uses a peerDependency with a more widely accepted version.
This should allow using the webpack plugin with various different versions of webpack.
Fixes #461
=> fix: Remove webpack dependency from webpack plugin

README.md
I noticed that the example code in the readme is using `stylex.apply` which doesn't seem to exist. Maybe an old version of the API?
=> Use stylex.props API in readme example

packages/babel-plugin/__tests__/stylex-transform-override-vars-test.js, packages/babel-plugin/src/visitors/stylex-create-theme.js
`stylex.createTheme` was almost always generating `UnknownFile__*` as debug classNames. Fixed it to use the actual file name, just like `stylex.create`.
=> fix: Fix the debug classNames for stylex.createTheme

packages/eslint-plugin/__tests__/stylex-sort-keys-test.js, packages/eslint-plugin/flow_modules/eslint/eslint-rule.js.flow, packages/eslint-plugin/package.json, packages/eslint-plugin/src/stylex-sort-keys.js
Adds a `fix` for `sort-keys` ESLint rule.
This implementation has one major limitation, however. The comments are not taken into consideration for the fixes. The major reason for this is that taking care of adjacent comments introduces many edge cases and too often we cannot guarantee persistent formatting of the edited text. The current fix works like this:
*Before:*
```typescript
foo: {
// bar
display: 'flex',
// baz
alignItems: 'center',
},
});
```
*After:*
```typescript
foo: {
// bar
alignItems: 'center',
// baz
display: 'flex',
},
});
```
Let's discuss this limitation -- would like to hear some opinions of how critical you think it is to move around the comments.
Fixes #415 
[Contribution …
=> feat: add `fix` to `eslint-plugin/sort-keys` rule

packages/esbuild-plugin/src/index.js
This PR fixes the return value of `onLoad` hook of the StyleX esbuild plugin (of the if branch when babel transform returns no code). Previously, it would return an object with property `code`, which resulted in undefined output of the plugin.
I did not create an issue for this since it's a very small fix.
=> Fix return value in esbuild plugin `onLoad` hook

apps/docs/docusaurus.config.js
This is current `og:image`.
`<meta data-rh="true" name="og:image" content="/img/stylex-cover-photo.png">`
`og:image` is url, not path. Therefore, this fixed it.
https://ogp.me/
=> fix: og:image

packages/babel-plugin/__tests__/stylex-transform-call-test.js, packages/babel-plugin/src/utils/evaluate-path.js, packages/babel-plugin/src/visitors/stylex-attrs.js, packages/babel-plugin/src/visitors/stylex-merge.js, packages/babel-plugin/src/visitors/stylex-props.js, packages/scripts/rewrite-imports.js, packages/stylex/src/StyleXTypes.js, packages/stylex/src/stylex.js
Found and fixed a bug in the optimisation step for optimising `stylex.props()` and `stylex()` calls within a `for-of` loop.
The custom `evaluate` logic would fail to bail out and throw a null pointer exception instead.
The fix was to check for that null value and bail out instead.
-----
Also, internally there are some rare example of non-existent styles (`styles.unknown`) being used which can cause the Babel plugin to throw an error.
Added a check to bail out instead of throwing an error for such cases and added a couple of test cases to verify that the fix works for `stylex()`, `stylex.props()` and `stylex.attrs()`.
=> fix: usage of styles in a loop and non-existent styles

apps/docs/docs/learn/06-ecosystem.mdx
Added Prettier plugin that I maintain to the ecosystem docs. The plugin helps to sort StyleX keys and can be used as an alternative to esbuild plugin sort keys auto-fix.
[Link to the plugin](https://github.com/nedjulius/prettier-plugin-stylex-key-sort)
N/A
N/A
=> docs: add `prettier-plugin-stylex-key-sort` to ecosystem docs

apps/docs/docs/learn/04-styling-ui/_category_.json, apps/docs/docs/learn/05-theming/_category_.json, apps/docs/docs/learn/06-static-types.mdx, apps/docs/docs/learn/07-ecosystem.mdx
Order of pages in "Learn" sidebar. Documenting the library's exported StaticTypes should come before documenting Ecosystem
=> Fix order of "Learn" documentation sidebar

packages/eslint-plugin/src/stylex-valid-styles.js
The ESLint Plugin lets you define custom limits for various properties. So far this can be:
- `*` for any value
- `string` for all strings
- `number` for all numbers
- or an array of specific options which can be globs.
However, using `['string', 'number']` would not work as expected, and instead treat `'string'` and `'number'` as constants.
Sometimes, it might be useful to accept any number along with specific strings or globs. This PR allows for such a pattern and will interpret `'string'` to mean the type string, and `'number'` to mean the type number, even when used within an array.
=> fix: Allow all strings/numbers along with specific values

apps/docs/docs/learn/07-ecosystem.mdx
Added babel plugin that i maintain to the ecosystem docs. The plugin allows user using `JSXAttribute` stylex to define inline style. might look like #534 
=> docs: ecosystem add `@stylex-extend/babel-plugin`

packages/babel-plugin/__tests__/stylex-transform-create-theme-test.js, packages/babel-plugin/__tests__/stylex-transform-define-vars-test.js, packages/babel-plugin/src/utils/evaluate-path.js, packages/babel-plugin/src/visitors/stylex-create-theme.js, packages/babel-plugin/src/visitors/stylex-define-vars.js, packages/dev-runtime/__tests__/stylex-transform-create-theme-test.js, packages/dev-runtime/__tests__/stylex-transform-define-vars-test.js, packages/shared/src/types/index.js
Adds the ability to give variables types using `stylex.types.*` functions.
- This enables animating things like the angle value in a `conic-gradient`. 
Most of the work for this was already done, this PR does some of the final bits of work to expose the functionality in the Babel plugin and adds a few tests.
---
This PR also fixes a bug where `stylex.keyframes` couldn't be used as a value within `stylex.createTheme`.
=> feat: Enable support for types for CSS vars

apps/docs/blog/2024-04-16-Release-v0.6.1.mdx, apps/docs/components/AnimatedGradientBox/AnimatedGradientBox.js, apps/docs/components/AnimatedGradientBox/tokens.stylex.js, apps/docs/docs/api/index.mdx, apps/docs/docs/api/javascript/types.mdx, apps/docs/docs/learn/05-theming/04-variable-types.mdx, packages/babel-plugin/__tests__/stylex-transform-create-theme-test.js, packages/babel-plugin/__tests__/stylex-transform-define-vars-test.js, packages/babel-plugin/src/utils/evaluate-path.js, packages/babel-plugin/src/visitors/stylex-create-theme.js, packages/babel-plugin/src/visitors/stylex-define-vars.js, packages/dev-runtime/__tests__/stylex-transform-create-theme-test.js, packages/dev-runtime/__tests__/stylex-transform-define-vars-test.js, packages/shared/src/types/index.js
Following up from the previous PR, this PR adds documentation for the `stylex.types.*` functions and adds a new blog post with release notes for `v0.6.1`.
=> docs: Add documentation for `stylex.types.*` functions

packages/stylex/src/StyleXCSSTypes.js
possible values can be a percentage from 50% to 200% https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch#values
=> support font-stretch percentage values

packages/rollup-plugin/.babelrc.cjs, packages/rollup-plugin/package.json
I had came to a need of stylex rollup-plugin in the cjs flavor. See this issue for relevant context. https://github.com/facebook/stylex/issues/451
So I added it. My PR is very much inspired by the current implementation in `packages/styles/package.json`
Fixes https://github.com/facebook/stylex/issues/451
The rollup-plugin now generates `lib/*` and `lib/es/*` folders. See screenshot:
I had run all the tests and lints. But as I'm unfamiliar with the repository. I'd gladly ask for a double check that I didn't break anything vital. 🙏 
What I have manually tested:
* The output `lib/es/index.mjs` is identical with the old `lib/index.js`
* The cjs flavor of the library was tested in my project and seems to be building correctly
Tagging @nmn as a follow-up to our discussion
[Contribution …
=> chore: Add cjs to rollup-plugin

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-valid-styles.js
Added `text-underline-offset` as a valid CSS property.
=> Text underline offset

packages/esbuild-plugin/package.json
Adds missing `babel-plugin-syntax-hermes-parser` dependency to esbuild plugin.
Fixes #576 
=> fix: add `babel-plugin-syntax-hermes-parser` dependency to esbuild plugin

packages/babel-plugin/__tests__/stylex-metadata-test.js, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/__tests__/stylex-transform-keyframes-test.js, packages/babel-plugin/__tests__/stylex-transform-logical-properties-test.js, packages/babel-plugin/__tests__/stylex-transform-value-normalize-test.js, packages/dev-runtime/__tests__/stylex-metadata-test.js, packages/dev-runtime/__tests__/stylex-transform-create-test.js, packages/dev-runtime/__tests__/stylex-transform-keyframes-test.js, packages/shared/__tests__/stylex-create-test.js, packages/shared/__tests__/stylex-keyframes-test.js, packages/shared/src/utils/normalize-value.js, packages/shared/src/utils/normalizers/zero-dimensions.js
Not dropping units for various `0` values leads to a significant increase in the size of the generated CSS file.
So this PR, brings back this particular strategy to drop units from `0` values while keeping the `fr` and `%` units and taking a more measured approach. If any other unit needs to be maintained, we can work on that in the future.
=> Revert "fix: Keep units for 0 values (#532)"

apps/cli-example/.stylex.json, packages/cli/src/modules.js
Fix cli fetchModule can't not working as expected.
None
- I notice cli has been in the main branch. So i based on the example directory to test the cli without json5. And i meet some bug when the `modules_EXPERIMENTAL` children is string literal. It will break `fetchModule` logic. According [fs.cpsync](https://nodejs.org/api/fs.html#fscpsyncsrc-dest-options) so we should set a state for filter option. 
- Fix cli example incorrect babel option.
=> fix(cli): when modules experimental item is string should be copy

package-lock.json, packages/cli/package.json, packages/cli/src/index.js, packages/cli/src/transform.js, packages/cli/src/watcher.js
The cli package is using `chalk` as a terminal output. However this package doesn't declare equivalent dependencies which risks ghost dependencies. And the most important ting is that the `chalk` doesn't support cjs. So we should find a package support esm/cjs. `picocolors` looks well but has too few features. So i think we can using `ansis` replace `chalk` and it will be smaller and faster.
None
=> chore: using ansis replace chalk

packages/nextjs-plugin/package.json
NextJS 15 has released a RC that depends upon this change.
=> Adds next@15 and next@15rc to the nextjs plugin's peer dependencies

packages/rollup-plugin/src/index.js
Fixes #402
There has been reports of the Rollup Plugin not playing well with `babel-env`. A fix was suggested in the issue above which is what this PR implements.
Still trying to reproduce the bug, but putting up this PR in the meantime for review.
=> fix: pass caller to babel within rollup plugin

packages/babel-plugin/__tests__/stylex-transform-create-theme-test.js, packages/babel-plugin/__tests__/stylex-transform-define-vars-test.js, packages/babel-plugin/src/utils/evaluate-path.js, packages/shared/__tests__/stylex-create-theme-test.js, packages/shared/__tests__/stylex-define-vars-test.js, packages/shared/src/stylex-define-vars.js
The main change proposed is to opt out of automatic variable name generation when the object keys used within `stylex.defineVars` starts with `--`.
There is often a desire to use variables defined within StyleX to be usable within a raw CSS file to set global styles. However, since the actual generated variable names created by StyleX are unknown until compile time, this process isn't developer friendly.
The only escape hatch today is to fallback to strings for using variables within StyleX and CSS. This means losing *all* the benefits provided by StyleX's theming APIs, such as type-safety and guaranteed default values.
There existing codebases that use CSS variable names as strings today and don't have a clear migration path to adopt StyleX's theming APIs. While it is easier to move to …
=> RFC: Maintain variable names for keys that start with "--"

apps/docs/docs/learn/03-installation.mdx
NextJS changed their configuration file to ESM, so a different file was needed. And the other changes were required to make it work. The original configuration didn't work. TBH, this needs to be reviewed by someone who understands the installation. This version works, but it's not clear if it's the correct fix.
=> Fixing NextJS installation instructions

packages/cli/src/config.js, packages/cli/src/index.js, packages/cli/src/options.js, packages/cli/src/transform.js
Added the `useCSSLayers` option to the CLI which, when `true`, generates a CSS bundle that uses CSS layers instead of the `:not(#\#)` polyfill.
=> CLI - add option to use CSS layers in the generated CSS file

packages/babel-plugin/__tests__/evaluation/stylex-import-evaluation-test.js, packages/babel-plugin/__tests__/stylex-transform-define-vars-test.js, packages/babel-plugin/src/utils/evaluate-path.js, packages/shared/__tests__/stylex-define-vars-test.js
Fixes bug when using literal keys (that start with `--`) on imported varGroups from `.stylex` files.
=> fix: Fix bug when using vars with literal keys

packages/shared/__tests__/stylex-first-that-works-test.js, packages/shared/src/stylex-first-that-works.js
Fixes #432 
Update `stylex.firstThatWorks` to work with variables and generate fallback values for variables.
Handles various edge-cases.
=> feat: allow using firstThatWorks for variable fallbacks

packages/babel-plugin/__tests__/evaluation/stylex-evaluation-test.js, packages/babel-plugin/src/utils/evaluate-path.js
Ensure the correctly binds the context when evaluating strings called with static method.
Fixes #555 
=> fix(babel-plugin): apply the right context for string static methods

packages/babel-plugin/__tests__/stylex-transform-logical-values-test.js, packages/shared/src/physical-rtl/generate-ltr.js, packages/shared/src/physical-rtl/generate-rtl.js
Fixes #627 
The `styleResolution: 'legacy-expand-shorthands'` configuration also converts logical properties to physical properties for supporting very old browsers.
Turns out that logical `text-align` has been supported in even the oldest browsers, so deleting the code that converts those logical values to physical ones.
=> fix: Stop polyfilling logical text-align

package-lock.json, package.json, packages/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/eslint-plugin/package.json, packages/eslint-plugin/src/stylex-valid-shorthands.js, packages/eslint-plugin/src/utils/splitShorthands.js
This PR iterates on a new lint rule for the handling of shorthands in stylex. 
- Here we are processing `background`, 'font' and `outline` properties.
- Because of the limitations of the parser in mapping exact styles, I'm leveraging https://www.npmjs.com/package/css-shorthand-expand to perform some of the parsing logic
- The output is transformed to stylex compatible syntax via regex parsing (stripping !important, camelCase)
On a broader scale, we want to add this fix within the js1 upgrade codemod. For the border styles, I'll explore leveraging the existing codemod instead of including it in this lint rule explicitly to avoid duplicate work.
This is a follow up to https://github.com/facebook/stylex/pull/614. 
Added tests to cover the following:
- Style objects with `background`, `font`, …
=> feat: Process font, background, and outline in shorthand lint rule

packages/cli/src/index.js, packages/cli/src/plugins.js, packages/cli/src/transform.js, packages/cli/src/watcher.js
Currently the CLI when used in watch mode has 3 issues.
1. If you have babel transform errors (such as when you made a type error with the typescript plugin), then the CLI will kill itself and exit.
2. Because we copy (and the subsequently delete) the modules_experimental to the input directory, this inadvertently triggers changes in watchman.
3. The only files initially picked up when started in watch mode are JavaScript files (or typescript, etc), which means existing non-JavaScript files are not copied over.
This PR fixes the issues by adding a catch to the function that compiles the input directory, excluding external node modules from recompiling via watchman, and ensuring that the CLI will recompile on changes to non-js files.
=> fix: handle watch mode errors and transform external module imports when options are specified

packages/eslint-plugin/src/stylex-sort-keys.js, packages/eslint-plugin/src/stylex-valid-shorthands.js
In v8.40.0 several properties on `context` were introduced as alternatives to a few methods (see: https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/). Accessing properties like `context.sourceCode`  is not backwards compatible with the older versions of eslint currently used in WWW, causing eslint to fail when either `sort-keys` or `valid-shorthands` is added ([D60950492](https://www.internalfb.com/diff/D60950492))
Ideally we should migrate WWW over to a newer version of eslint, but this would be a longer term fix that may involve other breaking changes with pre-existing lint rules.
1) Lint rule works in WWW
2) Shorthands test pass.
```
% npx jest shorthands
Test Suites: 1 passed, 1 total
Tests:       22 passed, 22 total
Snapshots:   0 total
Time: …
```
=> fix: Add legacy support for context.sourceCode

packages/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/eslint-plugin/src/stylex-sort-keys.js, packages/eslint-plugin/src/stylex-valid-shorthands.js, packages/eslint-plugin/src/utils/splitShorthands.js
This PR iterates on a new lint rule for the handling of shorthands in stylex. 
- Here we are processing border and related styles
- Original intention was to use the border shorthands codemod, but as there is support in https://www.npmjs.com/package/css-shorthand-expand, is lightweight to add for consistency and to keep all expansions in one rule
- The output is transformed to stylex compatible syntax via regex parsing (stripping !important, camelCase)
This is a follow up to https://github.com/facebook/stylex/pull/614 and https://github.com/facebook/stylex/pull/637
Added tests to cover the following:
- border-top
- border-right
- border-bottom
- border-left
- border-radius
As well as conditionally in these styles, if multi-value shorthand:
- border-width
- border-style
- border-color …
=> feat: Add border shorthand handling

packages/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/eslint-plugin/src/stylex-valid-shorthands.js
Previously we were indiscriminately expanding all multi-value shorthands to all four directions. Let's clean this up and split two-value shorthands like:
- margin: '10em 1em' -> marginInline:  '10em' and marginBlock:  '1em' 
- padding: '10em 1em' -> paddingInline:  '10em' and paddingBlock:  '1em' 
Check for number of values after splitting:
- If 1, return no error as before
- If 2, return inline and block values
- Else, return four directions
Added in test cases to ensure that two-value shorthands are accounted for.
=> fix: Process two-value shorthands appropriately

packages/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/eslint-plugin/src/stylex-valid-shorthands.js
Note: overrode https://github.com/facebook/stylex/pull/665 when merging into https://github.com/facebook/stylex/pull/664 and force pushing. Cherry picking onto main and merging directly
Previously we were indiscriminately expanding all multi-value shorthands to all four directions. Let's clean this up and split two-value shorthands like:
- margin: '10em 1em' -> marginInline:  '10em' and marginBlock:  '1em' 
- padding: '10em 1em' -> paddingInline:  '10em' and paddingBlock:  '1em' 
Check for number of values after splitting:
- If 1, return no error as before
- If 2, return inline and block values
- Else, return four directions
Added in test cases to ensure that two-value shorthands are accounted for.
[Contribution Guidelines](https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING. …
=> fix: process two-value shorthands appropriately in linter

packages/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/eslint-plugin/src/stylex-valid-shorthands.js, packages/eslint-plugin/src/utils/splitShorthands.js
The `css-shorthand-expand` library (https://www.npmjs.com/package/css-shorthand-expand) does not handle variable spacing correctly. Property values like `rgb(0, 0, 0` and `var(--example-var, 0)` are incorrectly being split (see: D61342957). Font values with quotations perform fine.
See: [D61342957](https://www.internalfb.com/diff/D61342957)
Let's preprocess the values to strip the whitespace in between parentheses that occur within comma separated parameters:
- `rgb(0, 0, 0)` -> `rgb(0,0,0)`
- `var(--example-var, 0)` -> `var(--example-var,0)`
We'll add back whitespaces after the commas within parentheses after splitting values if they are absent. (Prettier should handle this as well, but just for safety)
- `rgb(0,0,0)` -> `rgb(0, 0, 0)`
- `var(--example-var,0)` -> `var(--example-var, 0)` …
=> fix: Fix improper variable handing in css-shorthand-expand by pre-processing whitespace

packages/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/eslint-plugin/src/stylex-valid-shorthands.js, packages/eslint-plugin/src/utils/splitShorthands.js
As we added more properties, code became hard to maintain. Refactoring repeated logic for readability and ease of modification
```
$ npx jest shorthands
Test Suites: 1 passed, 1 total
Tests:       27 passed, 27 total
Snapshots:   0 total
Time:        1.866 s, estimated 2 s
Ran all test suites matching shorthands.
```
=> chore: dynamically generate shorthands property handlers

packages/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/eslint-plugin/src/stylex-sort-keys.js, packages/eslint-plugin/src/stylex-valid-shorthands.js, packages/eslint-plugin/src/utils/splitShorthands.js
Last change hopefully 🤞 WWW sync is still blocked so may as well get this all in
Processing properties with 2-4 duplicate values like `margin: "10px 10px 10px"`
Implementation:
-  Take the set of split values and check if length is 1
- Previously we filtered out shorthands where the input returned singular shorthand values by default. Now we check if the value matches the original to account for this edge case
Added tests for these use cases:
- margin: "10px 10px 10px"
- paddingInline: "20px 20px"
- padding: "25px 25px 25px 25px"
```
$ npx jest shorthands
Test Suites: 1 passed, 1 total
Tests:       27 passed, 27 total
Snapshots:   0 total
Time:        1.866 s, estimated 2 s
Ran all test suites matching shorthands.
```
[Contribution …
=> fix: process duplicated single shorthands

.github/workflows/performance.yml, package-lock.json, packages/scripts/package.json, packages/scripts/size-compare.js, packages/scripts/size.js
Consolidate results and produce simpler markdown table
=> Refactor bundle size workflow

packages/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/eslint-plugin/src/stylex-valid-shorthands.js, packages/eslint-plugin/src/utils/splitShorthands.js
Improper or check causing numeric values to trigger false positives: replacing `if A == (x || y || z)` with `if (A == x || A == y || A == z)`.
Also, added number -> string -> number reconversion. This is hard to capture on tests, discovered when linting on WWW (borderRadius: 5 -> borderRadius: '5') 
Manually ported over changes into WWW and tested
=> fix: Fix check for single value shorthands

packages/babel-plugin/__tests__/stylex-transform-create-theme-test.js, packages/dev-runtime/__tests__/stylex-transform-create-theme-test.js, packages/shared/__tests__/stylex-create-theme-test.js, packages/shared/src/stylex-create-theme.js
Simple bug-fix for cases where we can't enforce a single CSS bundle for defining variables.
=> fix: Ensure themes have higher specificity than default var values

packages/cli/src/transform.js
A previous PR #680 had mysterious CI errors. This is a second attempt at the same change.
=> fix: [CLI] Handle errors while deleting files gracefully

package-lock.json, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/shared/__tests__/stylex-create-test.js, packages/shared/src/transform-value.js
fixes #689 
For convenience and to match the behaviour of React Native, StyleX allows the usage of numbers as values and tries to automatically add units where they make sense.
The issue, however, is that for any unknown value StyleX assumes it to be a length and adds `px` unit by default. While we should probably revisit that behaviour itself, for now, this PR adds a special case for CSS variables and leaves numbers used as values for CSS variables keys as is.
=> fix: Don't add units number values used for variables

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-valid-styles.js
A very small change to allow `fieldSizing` in the ESLint rule.
=> fix: (eslint) Add fieldSizing as a valid prop

packages/eslint-plugin/__tests__/stylex-enforce-extension-test.js, packages/eslint-plugin/src/stylex-enforce-extension.js, packages/shared/src/preprocess-rules/flatten-raw-style-obj.js
This ESLint rule ensures consistency in file naming conventions when exporting `stylex.defineVars`. 
Specifically:
- Files that export `stylex.defineVars` must end with `.stylex.jsx` or `.stylex.tsx` 
- Files that do not export `stylex.defineVars` must not use the `.stylex.jsx` or `.stylex.tsx` extensions
- Users can configure the file extension via a themeFileExtension option (e.g., `.custom.jsx`), defaulting to `.stylex.jsx`.
Valid cases:
- Files with `stylex.defineVars` export correctly using `.stylex.jsx`, `.stylex.tsx`, or custom extensions.
- Files without `stylex.defineVars` export using non-.stylex extensions.
Invalid cases:
- Files exporting `stylex.defineVars` without the correct extension.
- Files not exporting `stylex.defineVars` but using `.stylex.jsx/.tsx` or custom …
=> feat: new lint rule to enforce stylex file extension

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-valid-styles.js, packages/stylex/src/StyleXTypes.d.ts
Found some missing pseudo classes while commenting on #137.
Probably falls somewhere under #135.
See diff.
Refs on pseudo elements:
- https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-slider-thumb
- https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-slider-runnable-track
- https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-thumb
- https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-track
- https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-progress
- https://www.smashingmagazine.com/2021/12/create-custom-range-input-consistent-browsers/
- https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/
- https://stackoverflow.com/questions/18389224/how-to-style-html5-range-input-to-have-different-color-before-and-after-slider …
=> fix: Add missing CSS pseudo elements to types and ESLint

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-valid-styles.js, packages/shared/__tests__/flatten-raw-style-objects/legacy-shorthand-expansion-test.js, packages/shared/src/preprocess-rules/legacy-expand-shorthands.js, packages/stylex/src/StyleXCSSTypes.js
Update the StyleX Flow types to allow additional valid `scrollSnapType` values.
Update the ESLint rule to allow `containIntrinsic*` properties.
=> fix: Update allowed styles with Flow and ESLint

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-valid-styles.js
For some reason the valid-styles tests don't actually fail even if they are invalid.
=> Add focus-within

apps/docs/docs/learn/03-installation.mdx, package-lock.json, packages/babel-plugin/package.json, packages/babel-plugin/src/utils/state-manager.js, packages/esbuild-plugin/README.md
I author esm and the babel plugin wasn't recognizing my imports.
I tested this in my app and it resolves the files now.
The package I use is pretty lenient when It comes to imports. It might be able to be used instead of the other file path resolvers too.
=> add esm resolver

packages/babel-plugin/__tests__/evaluation/stylex-fn-obj-evaluation-test.js, packages/babel-plugin/__tests__/evaluation/stylex-import-evaluation-test.js, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/__tests__/stylex-transform-legacy-shorthands-test.js, packages/babel-plugin/src/visitors/stylex-create/index.js, packages/babel-plugin/src/visitors/stylex-create/parse-stylex-create-arg.js, packages/shared/__tests__/flatten-raw-style-objects/legacy-shorthand-expansion-test.js, packages/shared/__tests__/gen-css-test.js, packages/shared/__tests__/stylex-create-test.js, packages/shared/src/preprocess-rules/PreRule.js, packages/shared/src/preprocess-rules/flatten-raw-style-obj.js, packages/shared/src/preprocess-rules/index.js, packages/shared/src/stylex-create.js, packages/shared/src/transform-value.js
Dynamic Styles in StyleX are expressed as minimal arrow functions that return an arrow expression. These styles are then compiled into a function that returns a tuple of two objects — an object of static classNames and an object of inline styles that *only* sets some CSS variables.
The CSS variables defined as inline styles are used in the statically generated CSS as values for the properties that are to have a dynamic value.
In this PR, the biggest change is that the object of static classNames is slightly more dynamic than before. Instead of statically returning classNames for all properties, the classNames are now only returned conditionally *when* the dynamic value passed into the function for that particular party is *not* null or undefined.
In short this means that after this …
=> fix: more efficient dynamic styles

packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/shared/__tests__/stylex-create-test.js, packages/shared/src/preprocess-rules/PreRule.js
Previously all pseudo elements and pseudo classes would be sorted alphabetically. This had the unfortunate side-effect that all pseudo classes, both outside and inside the pseudo element would be applied on the same element.
Now only consequent runs of pseudo classes will be sorted and pseudo elements will maintain
their positions.
Fixes #550
=> fix: Maintain nesting order of pseudo elements vs pseudo classes

packages/babel-plugin/src/visitors/stylex-create-theme.js, packages/babel-plugin/src/visitors/stylex-create/index.js, packages/babel-plugin/src/visitors/stylex-create/parse-stylex-create-arg.js, packages/babel-plugin/src/visitors/stylex-define-vars.js, packages/babel-plugin/src/visitors/stylex-keyframes.js
Using code frame errors will show the dev generally where the problem is:
- I'm not familiar with the repo. Wouldn't be offended if you close the PR and replicate with preferred style.
=> use code frames for errors for babel plugin

packages/shared/__tests__/stylex-create-test.js
This PR just updates a single test to show that existence of a bug.
notice that `color:blue` has the same className for `::before:hover` and `:hover::before`.
=> chore: show the existence of bug

packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/shared/__tests__/stylex-create-test.js, packages/shared/src/convert-to-className.js, packages/shared/src/preprocess-rules/PreRule.js, packages/shared/src/utils/rule-utils.js
We recently fixed an issue with how pseudo selectors are sorted in StyleX to ensure we don't accidentally mix up pseudo classes and pseudo elements incorrectly. 
However, while we fixed the generated rules in the previous PR, the string hashed to generate a unique className was still using the old logic. This would mean that, e.g. if you used both `::before:hover` *and* `:hover::before` selectors in your styles for the exact same property and value, both rules would generate the same className.
(TODO: Create a separate commit to actually demonstrate this edge-case in a test)
This PR updates the logic used when generating the className to match the logic used when generating the CSS rule to fix this issue.
Fixes #749
=> fix: ensure unique classNames for pseudo classes & elems

packages/babel-plugin/src/utils/state-manager.js
Small fix to make `esmResolve` work reliably when resolving themes across packages in a mono-repo.
=> fix: convert esm-resolve paths to absolute paths

apps/docs/.eslintrc.js, apps/docs/package.json, package-lock.json, package.json, packages/eslint-plugin/__tests__/stylex-no-unused-test.js, packages/eslint-plugin/src/index.js, packages/eslint-plugin/src/stylex-no-unused.js
Addresses task [ESLint: find unused styles #702](https://github.com/facebook/stylex/issues/702?fbclid=IwZXh0bgNhZW0CMTEAAR2MT8Ix_O_v1dR3d67dGTsuDgK6e_Z7zB0YeIa2Ks6JUMXAi-O8eaep-90_aem_UI7ZN09GF1cJd6VKzo0D_Q).
Identify all styles that 1) not used; 2) not exported. The feature also allow auto fix by removing fields that are unused.
```typescript
import stylex from 'stylex';
// exported, considered all used
main: {
borderColor: {
default: 'green',
':hover': 'red',
'@media (min-width: 1540px)': 1366,
},
borderRadius: 10,
display: 'flex',
},
dynamic: (color) => ({
backgroundColor: color,
})
});
// not exported, not used, will report warning `Unused style detected: stylesUnused.maxDimensionsModal`
const stylesUnused = stylex.create({
maxDimensionsModal: { …
```
=> feat: add no-unused eslint rule to find unused styles

packages/eslint-plugin/src/stylex-no-unused.js, packages/eslint-plugin/src/stylex-sort-keys.js, packages/eslint-plugin/src/stylex-valid-shorthands.js, packages/eslint-plugin/src/utils/getSourceCode.js
As per reviewer comment left by @mellyeliu on PR [`feat: add no-unused eslint rule to find unused styles`](https://github.com/facebook/stylex/pull/767#discussion_r1833640097), multiple eslint rule definition files are using identical conditional logic to get source code from Rule context such that we are backwards comparable with older eslint versions. This PR extract this logic into a separate util function so that it can be reused.
Fixes #767 
- `npx jest *` running all test files inside `estlint-plugin` folder, all tests still passing
=> chore: extract eslint get souce code to util

apps/cli-example/.stylex.json5, packages/babel-plugin/flow_modules/@babel/types/index.js.flow, packages/cli/__tests__/__mocks__/snapshot/components/button.js, packages/cli/__tests__/__mocks__/snapshot/index.js, packages/cli/__tests__/__mocks__/snapshot/pages/home.js, packages/cli/__tests__/__mocks__/snapshot2/components/button.js, packages/cli/__tests__/__mocks__/snapshot2/index.js, packages/cli/__tests__/__mocks__/snapshot2/pages/home.js, packages/cli/flow_modules/@babel/types/index.js.flow, packages/cli/src/config.js, packages/cli/src/index.js, packages/cli/src/options.js, packages/cli/src/plugins.js, packages/cli/src/transform.js
1. Added two new configuration options: `babelPluginsPre` and `babelPluginsPost` that are lists of babel plugins that can be run before or after the StyleX plugin during transformation.
2. Changed the injection of the CSS import to be insert *after* all the other import statements. This is to make it easier to use your CSS file for reset styles.
=> feat: CLI can use additional Babel plugins

apps/nextjs-example/app/layout.tsx, apps/nextjs-example/app/stylex.css, apps/nextjs-example/babel.config.js, apps/nextjs-example/package.json, apps/nextjs-example/postcss.config.js, package-lock.json, packages/postcss-plugin/README.md, packages/postcss-plugin/package.json, packages/postcss-plugin/src/builder.js, packages/postcss-plugin/src/bundler.js, packages/postcss-plugin/src/index.js
- Adds a PostCSS Plugin named `@stylexjs/postcss-plugin` as described in the linked issue.
- Updates nextjs-example to use` @stylexjs/postcss-plugin`
Fixes https://github.com/facebook/stylex/issues/779
The implementation is mostly based on [postcss-react-strict-dom](https://github.com/javascripter/postcss-react-strict-dom) that I wrote but have decided to convert it to JavaScript instead of TypeScript to make it suitable for this repository.
The plugin is rather simple so I didn't add Flow types for now (same as the current nextjs-plugin).
I've described the overview of this plugin approach [here](https://github.com/facebook/react-strict-dom/issues/236#issuecomment-2474722120).
This PR:
Original:
[Contribution Guidelines](https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING.md …
=> feat: add postcss-plugin

packages/eslint-plugin/src/stylex-valid-styles.js
Adds the missing property to the ESLint rule. That's it.
=> fix: add support for view-transition-name in ESLint valid-styles rule

packages/babel-plugin/__tests__/evaluation/stylex-import-evaluation-test.js, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/src/visitors/stylex-create/index.js
Addresses task https://github.com/facebook/stylex/issues/734?fbclid=IwZXh0bgNhZW0CMTEAAR2-QvBRO5HXoBYI-LmCO1benFCf76i8rsQqF7eQ9C3elQYx859Zpkr4rRI_aem_hLD_maBEZrcTD5svWp7J3A.
Generate `@property` declarations for all variables that are created for dynamic styles and declare them as not inheriting. Increase stylex variable compiler efficiency by disabling all dynamic styles from cascading down from the node defining the variable.
Fixes #734 
`npx jest stylex-transform-create-test`
Test file [stylex-transform-create-test.js](https://github.com/facebook/stylex/compare/feat/dynamic-styles-inherits-false?expand=1#diff-1ae52714c572f4282c394af92227b4198e93ffdccd6bf7c38129b36f09250280) should have `@property` injection added for all stylex dynamic styles.
[Contribution …
=> feat: dynamic styles set inherits to false

packages/cli/src/files.js
Fixes a Windows-specific bug where the CLI injects import statements with backslashes.
Fixes #774
=> fix: Use POSIX paths when inserting import statements

packages/babel-plugin/src/visitors/stylex-create/index.js, packages/cli/src/files.js
Actually fixes #774
I made a mistake while rebasing the previous PR and the problem was still not fixed.
=> fix: do not use path.posix.relative

packages/cli/__tests__/compile-stylex-folder-test.js
Follow up to https://github.com/facebook/stylex/pull/790 and https://github.com/facebook/stylex/pull/792
Let's clean up the tests and move to async functions 
=> chore: refactor cli cache tests to be async

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-valid-styles.js
As per internal discussions, let's add an autofix into the valid-styles rule. Some of this logic exists in the valid-shorthands rule, but it makes sense to move the erroring here for the repos in which valid-shorthands is not enabled.
I've kept the descriptor in the autofix short and simple to avoid clutter on a lint error that will likely crop up a lot, but can also link to https://fb.workplace.com/groups/stylexfyi/posts/1769833193785624 or something related as context. Open to feedback here!
As a next step, we should work towards splitting up the valid-styles rule into more discrete chunks to increase the granularity of error reporting/messaging (perhaps after the codemodding)
Added tests for the following styles: 
- marginStart -> marginInlineStart
- marginEnd -> marginInlineEnd
- …
=> feat: add autofix for logical to inline properties in valid-styles rule

packages/babel-plugin/__tests__/evaluation/stylex-import-evaluation-test.js, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/src/visitors/stylex-create/index.js
This PR is a quick fix to resolve `AtRuleBodyInvalid` `SyntaxError: Invalid @ rule body` error caught in while doing task #799 ([see discussion](https://github.com/facebook/stylex/issues/799#issuecomment-2537296024)). This is a bug caused by previous PR [feat: dynamic styles set inherits to false #794](https://github.com/facebook/stylex/pull/794/files#diff-879871ad922cfbbd8d59d46cd33adfccaa6305fb88c5b22dfdd5c06f5c945bf5R130), where we did not include mandatory descriptors `syntax` and `initial-value` for `@property` (see MDS docs [@property](https://developer.mozilla.org/en-US/docs/Web/CSS/@property) [initial-value](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/initial-value) [syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/syntax)).
> BEFORE
``` …
```
=> chore: fix @property inherits syntax

apps/rollup-example/index.js, apps/rollup-example/lotsOfStylesDynamic.js, typos.toml
This PR added a feature as requested by task #799 , adding dynamic styles to benchmark  fixture, which can then be used by [benchmark workflow](https://github.com/facebook/stylex/blob/main/.github/workflows/performance.yml) on each PR to check performance. This new addition can also help us quantify any performance improvement made to compile dynamic styles, in addition to existing support for static style(e.g. [feat: dynamic styles set inherits to false #794](https://github.com/facebook/stylex/pull/794)).
Fixes #799 
We do:
- adding additional style examples to fixture
- run `npm run build -w rollup-example` to update `bundle.js`
- we observe generated `bundle.js` to contain the new dynamic styles and observe a size increase when running `./packages/scripts/size.js` script
**[BEFORE]** …
=> feat: add dynamic styles to benchmarks fixture

packages/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/eslint-plugin/src/utils/splitShorthands.js
Certain complex shorthand values like `'4px solid var(--fds-gray-10)'` seem to trip up the css-shorthand-expand package, which defaults to returning null. Let's handle the cases by prematurely returning and not providing an autofix in such cases.
**_Still identifying repros to make the test more robust_**
=> fix: fix valid-shorthands object casting error on css-shorthand-expand null return

packages/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/eslint-plugin/src/stylex-valid-shorthands.js, packages/eslint-plugin/src/utils/splitShorthands.js
When using the `preferInline` config, we were expanding margin/padding to equivalent inline logical properties. However, we overlooked applying the same transform to certain border properties.
The change introduced here extends the inline logical transformation to border properties (specifically borderWidth, borderStyle, and borderColor) by applying the same logic used for margin and padding. We take the output from `css-shorthand-expand` and apply a transform to the physical properties returned.
Added test expansions for borderWidth, borderStyle, and borderColor with `preferInline` set to default (false) and true
=> fix: add inline processing for borderWidth, borderColor, borderStyle to valid-shorthands

apps/nextjs-example/app/CardTokens.stylex.ts, apps/nextjs-example/babel.config.js, apps/nextjs-example/components/Card.tsx, packages/babel-plugin/__tests__/stylex-transform-create-theme-test.js, packages/babel-plugin/__tests__/stylex-transform-define-vars-test.js, packages/babel-plugin/src/utils/__tests__/state-manager.test.js, packages/babel-plugin/src/utils/state-manager.js
`unstable_moduleResolution.rootDir` should now always be optional. 
I tested this change with the `nextjs-example` as our tests don't read files for now.
Fixes #818
=>  fix: Babel plugin should no longer require `unstable_moduleResolution.rootDir`

packages/babel-plugin/__tests__/stylex-transform-pre-plugin-test.js, packages/babel-plugin/src/index.js
StyleX is sometimes used alongside other code transformation that can generate StyleX code. Examples include the React-Strict-DOM Babel plugin and `tailwind-to-stylex`.
The StyleX compiler has to do multiple passes of the entire tree to compile and then optimize the code. Previously, some of the transformations happened using a `path.traverse` in `Program:enter`. Because of how Babel runs multiple plugins, this meant that StyleX would often transform *before* previous transforms were completed. This could result incomplete compilation.
This change moves some code around to move things to the normal tree traversal or `Program:exit`. This will ensure that StyleX can consume any code generated by previous transforms.
> [!NOTE]
> There is no functional change to the output of the Babel …
=> fix: avoid traversing on `Program:enter`

packages/rollup-plugin/__tests__/index-test.js, packages/rollup-plugin/src/index.js
Until now I found that no one has implemented it.
Fixes #778 
=> feat: rollup plugin support generate file with pattern

package-lock.json, packages/babel-plugin/package.json, packages/babel-plugin/rollup.config.mjs, packages/babel-plugin/src/utils/state-manager.js
In the past we used `esm-resolve` to resolve es-based projects. But we need write two sets of code for `cjs` and `esm`. In `cjs` we using `require.resolve` and in other we using `esm-resolve` to create a resolve to do this. And in community [`@dual-bundle/import-meta-resolve`](https://www.npmjs.com/package/@dual-bundle/import-meta-resolve) allows us to avoid writing 2 sets of code.
=> Feat: Using `@dual-bundle/import-meta-resolve` replace `esm-resolve`

apps/nextjs-example/app/CardTokens.stylex.ts, apps/nextjs-example/components/Card.tsx, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/shared/src/convert-to-className.js
...when being assigned a value in `stylex.create`.
Fixes #821
=> fix: preserve camelCased Variable names 

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-valid-styles.js
`@stylexjs/valid-styles` erroneously reports an issue when the file import includes a file extension, e.g.,
```ts
import * as stylex from '@stylexjs/stylex';
import { vars } from './vars.stylex.ts';
root: {
fontFamily: vars.primaryFont,
},
});
```
See the linked issue below for more details.
Fixes https://github.com/facebook/stylex/issues/769
I added 1 test
=> fix(@stylexjs/eslint-plugin): Remove false positive in valid-styles when import contains extension

apps/docs/docs/learn/06-recipes/01-context-driven-styles.mdx
I got hung up reading the docs due to an accidental omission of the word "be." Also, to make the last part of this sentence clearer that it's regarding the advantages of the StyleX way of doing things and not the legacy way, I changed the word "where" to "as" and made it a dependent clause with a comma.
N/A
N/A
=> Typo fix in docs

packages/babel-plugin/__tests__/evaluation/stylex-import-evaluation-test.js, packages/babel-plugin/src/utils/state-manager.js
In a TypeScript project using `moduleResolution: 'node16' | 'nodenext'`, relative imports must include the file extension because of the Node.js ESM resolver [requires file extensions](https://nodejs.org/docs/latest-v18.x/api/esm.html#mandatory-file-extensions).
Consider the following:
```ts
import * as stylex from '@stylexjs/stylex';
import { vars } from '../vars.stylex.js';
import { theme } from '../theme.stylex.js';
root: {
backgroundColor: vars.primary,
},
});
```
The babel plugin currently attempts to verify whether these relative import files actually exist. It does this by trying to resolve the import string relative to the source file. First by checking the import string itself, then checking each of the valid file extensions in turn …
=> fix(@stylexjs/babel-plugin): Support .js resolved file extension imports from .ts files

packages/cli/src/cache.js
`murmurhash` is in fact faster than `crypto`, and we don't need the added security for caching. let's switch for consistency
tests pass, yolo
=> feat: replace crypto with murmurhash for cli caching

packages/babel-plugin/src/utils/state-manager.js
Before i replaced esm resolve but i ignored windows user :( . This pull request is a fix for windows.
Fixes #848 
According [url spec](https://url.spec.whatwg.org/#url-class). pathname is start with slash. It's not right for windows, and using `url.pathToFileURL` can return the true path
=> fix(babel-plugin): import resolve should respect windows system

packages/cli/src/cache.js
Replace `require()` function with ESM.
=> fix: use ESM imports in CLI

packages/cli/__tests__/compile-stylex-folder-test.js, packages/cli/src/cache.js, packages/cli/src/transform.js
Oversight in https://github.com/facebook/stylex/pull/792 where `readCache` is still reading from default cache path
Added more comprehensive testing, previously we were just ensuring the correct cache files were written, not checking the read functionality
=> fix: fix readCache to use custom cache path when set

packages/cli/__tests__/compile-stylex-folder-test.js, packages/cli/src/cache.js, packages/cli/src/transform.js
Let's invalidate the cache whenever StyleX config options change:
- Stringify config (without input/output paths, as accounted for) into key sorted JSON, hash output, add to cache check
Added test for config change
=> fix: add cache invalidation on config change

packages/babel-plugin/__tests__/evaluation/stylex-import-evaluation-test.js, packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/src/visitors/stylex-create/index.js
When creating `@property` declarations for CSS variables created for dynamic styles, should not contain `initial-value: "*"`.
This actually sets the variables to `"*"`. 
This is invalid but we didn't notice because most CSS properties don't accept string values (wrapped in quotes) anyway.
However, when using it for `content` or `font-family` this results invalid styles.
This PR just removes this line.
=> fix: invalid initial-value in @property

apps/docs/docs/learn/06-recipes/03-descendant styles.mdx, apps/docs/docs/learn/06-recipes/04-reset-themes.mdx, apps/docs/docs/learn/06-recipes/05-merge-themes.mdx, apps/docs/docs/learn/06-recipes/06-light-dark-themes.mdx
Adds three more recipes all related to theming.
Explains how using `stylex.createTheme(vars, {})` creates a theme that resets variables to their default values.
Shows how to define object constants outside `stylex.createTheme` calls to be able to reuse and merge objects and avoid repetition.
Talks about using the `light-dark()` function to control the color-scheme instead of defining three `light`, `dark` and `system` themes explicitly.
=> docs: Add theming recipes

packages/stylex/src/VarTypes.js, packages/stylex/src/stylex.js, packages/stylex/src/util-types.js, packages/stylex/type-tests/theming1.js.flow
Fixes #857
New types are exported such as `stylex.Color` and `stylex.Length`.
These are the return types of the `stylex.types.*` function. So, for example,
- `stylex.types.color("red")` is of type `stylex.Color<string>`
Should the types be under `stylex.types` instead?
- `stylex.types.color("red")` would be of type `stylex.types.Color<string>`
=> feat: exported return types of 'stylex.types.*' fns

packages/cli/__tests__/compile-stylex-folder-test.js
In the refactor here https://github.com/facebook/stylex/pull/804 we should be wrapping `done()` in a `finally` block to prevent the test from hanging if an error is thrown.
Currently, if an assertion fails (e.g., an `expect()` check fails), the test times out instead of displaying the failure, since `done()` is never called.
With try/catch/finally:
- Assertions properly fail the test (catch ensures `done(err)` is called)
- Test always completes, even if an error occurs
This prevents Jest from hanging indefinitely and ensures failures are reported correctly
Tests pass on main.
In https://github.com/facebook/stylex/pull/875, tests no longer timeout, but accurately display the error:
```
expect(received).toEqual(expected) // deep equality
- Expected  - 19
+ Received  + 18
@@ -14,30 +14,29 @@ …
```
=> fix: fix jest timeout in cli cache tests

packages/shared/__tests__/split-value-test.js, packages/shared/src/preprocess-rules/legacy-expand-shorthands.js, packages/shared/src/utils/split-css-value.js
Fixed the expansion handling of border-radius shorthand values containing the '/' separator.
Fixes #730 
- Modified the splitValue function to handle nodes containing '/' by merging them with adjacent nodes
- Example: '1px / 2px' is now correctly processed as borderStartStartRadius: '1px / 2px'
- Added test cases in packages/shared/__tests__/split-value-test.js
=> fix: Properly parse multi-value shorthand with slash

packages/shared/__tests__/split-value-test.js, packages/shared/src/preprocess-rules/legacy-expand-shorthands.js, packages/shared/src/utils/split-css-value.js
facebook/stylex#859 is causing undefined type errors, likely from accessing a property on an undefined variable. Reverting as we investigate cause.
=> Revert "fix: Properly parse multi-value shorthand with slash"

packages/webpack-plugin/__tests__/index-test.js, packages/webpack-plugin/src/index.js
Remove the Babel plugin that converts ESM to CJS from the Webpack plugin.
=> fix: remove esm->cjs conversion from Webpack plugin

apps/docs/docs/api/configuration/babel-plugin.mdx, apps/docs/docs/api/configuration/dev-runtime.mdx, apps/docs/docs/api/configuration/postcss-plugin.mdx, apps/docs/docs/api/index.mdx
Adds docs for the postcss-plugin and updates the docs for the babel-plugin to include `debug`. Also remove deprecated features from these docs.
=> Update API configuration docs

packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-valid-styles.js
Some asks and confusion popping up like in [D69623973](https://www.internalfb.com/diff/D69623973). Let's add in border autofixes for the following properties:
- borderStartWidth -> borderInlineStartWidth
- borderEndWidth -> borderInlineEndWidth
- borderStartStyle -> borderInlineStartStyle
- borderEndStyle -> borderInlineEndStyle
- borderStartColor -> borderInlineStartColor
- borderEndColor -> borderInlineEndColor
Follow up to https://github.com/facebook/stylex/pull/805
Added tests 
=> feat: add border autofixes to valid styles

packages/babel-plugin/src/utils/state-manager.js, packages/shared/src/common-types.js, packages/shared/src/convert-to-className.js, packages/shared/src/utils/default-options.js
As discussed, let's decouple debug class names and `data-stylex-src` attributes by creating a new config option `debugClassNamePrefix` to create more optionality on using `data-stylex-src` without debug classnames
The only thing worth considering is we now have chaining that looks like this: debugClassNamePrefix falls back to debug, which falls back to dev, which feels a bit opaque and potentially confusing.
Tests pass?
=> feat: decouple debug class names and data-* attributes

.github/workflows/tests.yml
Let's use `npm ci` over `npm install` for faster, more reliable CI workflows 
=> chore: update CI to use `npm ci`

.github/workflows/tests.yml
Vercel builds seem to be erroring with https://github.com/facebook/stylex/pull/906, let's switch back to debug. `package-lock.js` in main may be in a weird state
=> chore: revert npm ci 

packages/postcss-plugin/src/builder.js
Now `postcss plugin` don't pass the full path for babel transform. So if we using this plugin in a mono repo we can't get the right path for translate. 
Note at the first part of the content is the file id get from vite. the second part is get from postcss plugin.
Why cause it?
because i pass the rootDir for plugin. ( I'm not sure if this is as expected) The rootDir is the monorepo root. Based on this, it may be cause erros in a mono repo because the generated class names
will not match.
https://github.com/facebook/stylex/blob/dc49bae074f3906c394a149004b88363bc696a08/packages/babel-plugin/src/utils/state-manager.js#L552
=> fix: should respect filename for babel 

packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/src/utils/add-sourcemap-data.js
Styles with string or number keys have different types in the Babel AST. This patch correctly generates sourcemap data for those key types. And it ensures that the compiled style is always preserved even if sourcemap data isn't generated.
Fix #919
Close #920
=> Fix style compilation for string and number keys

vercel.json
This PR brings back the `vercel.json` file that is sets the hosting configuration to enable cross origin policies which are needed for the playground to work.
=> fix: bring back cross-origin config for fixing playground

packages/babel-plugin/src/index.d.ts
Added a temporary `.d.ts` file for stylex babel plugin. This overrides the output of 
```ts
export default EXPORT_DEFAULT_DECLARATION
```
to
```ts
export = $$EXPORT_DEFAULT_DECLARATION$$;
```
Although this doesn't looks like a good solution. Need to find a good solution later.
Fixes # [(issue)](https://github.com/facebook/stylex/issues/889)
After change types works fine
=> fix: add .d.ts for stylex babel plugin to resolve cjs export and typescript mismatch

packages/babel-plugin/__tests__/stylex-transform-define-vars-test.js, packages/babel-plugin/src/utils/evaluate-path.js, packages/shared/src/stylex-define-vars.js
Fixes #937 
In `debug` mode we add prefixes to the generate variable names to make them more readable. The prefixes use the object keys that you use in your `stylex.defineVars` calls.
This PR escapes special characters (etc) to ensure that the generated variable names stay valid. Even if you use special characters in your `stylex.defineVars` calls.
=> fix: Escape special characters from debug var names

packages/eslint-plugin/README.md
From discussions with ESLint oncall StyleX lint rules often provide lots of confusion, particularly around logical -> standard properties. We've previously added autofixes, but updating rules documentation here and internally to reduce confusion
=> chore: improve documentation for lint rules

packages/babel-plugin/__tests__/stylex-validation-declarations-test.js, packages/babel-plugin/src/visitors/stylex-create/index.js, packages/docs/docs/learn/04-styling-ui/01-defining-styles.mdx, packages/shared/src/messages.js
Explicitly disallow spreads within `stylex.create()` calls in the docs for planned js runtime merging optimizations. Update docs to reflect this.
Added test with object spread in `stylex.create()` to ensure throw.
=> chore: disallow spreading in stylex.create

packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/src/utils/add-sourcemap-data.js
Adds type-safe key matching in addSourceMapData using explicit Babel typeguards (`t.isIdentifier`, `t.isStringLiteral`, `t.isNumericLiteral`). This improves type safety and prevents runtime errors  in edge cases like object spreads (disallowed now, but theoretical) or computed keys, as the AST shape can vary and .name/value may be undefined
```
npm run test -w @stylexjs/babel-plugin
```
=> fix: add type safety to sourcemap construction

packages/eslint-plugin/README.md, packages/eslint-plugin/__tests__/stylex-no-legacy-media-queries-test.js, packages/eslint-plugin/src/index.js, packages/eslint-plugin/src/stylex-no-legacy-media-queries.js
This diff adds a new eslint rule for flagging usage of stylex's legacy media query/pseudo class syntax that looks like this:
```js
root: {
width: '100%',
'@media (min-width: 600px)': {
width: '50%',
}
}
});
```
The lint messages direct developers to instead use this syntax:
```js
root: {
width: {
default: '100%',
'@media (min-width: 600px)': '50%'
}
}
});
```
The new lint rule is notably not auto-fixable in this diff but that is something I'm going to be working on next.
I introduced new eslint "RuleTester" tests that are passing.
=> feat: add new eslint rule for flagging legacy media query/pseudo class syntax

packages/style-value-parser/src/at-queries-from-tokens/__tests__/media-query-test.js, packages/style-value-parser/src/at-queries-from-tokens/media-query.js, packages/style-value-parser/src/properties/__tests__/border-radius.test.js
Addes a new `normalize` function in the parser to flatten nested ands and remove unnecessary negations (negations % 2) 
To flatten ands:
- When the function encounters an `and` rule, it loops over each of its child rules
- If a child rule is also an `and` rule, its own child rules are merged (or "spread") into the parent `and` rule
- Results in one `and` rule containing all the conditions on the same level
Remove nested nots:
- When a `not` rule is encountered, the function recursively normalizes its inner rule and counts consecutive `not` wrappers.  
- If the count is **even**, the negations cancel out, and the inner rule is returned as if no `not` was applied
- If the count is **odd**, the result is a single `not` wrapping the innermost rule
- This cancellation avoids unnecessary …
=> feat: improve media query parser implementation

packages/stylex/src/StyleXTypes.js
The Flow team is looking into killing $Rest now that Omit exists for a long time. This PR replaces these in stylex.
=> Replace $Rest in stylex

packages/babel-plugin/__tests__/stylex-transform-create-test.js, packages/babel-plugin/__tests__/stylex-transform-stylex-props-test.js
Improve test coverage and make navigating the suite easier.
* Rename tests and organize into groups.
* Consolidate redundant tests.
* Move a 'props' tests to props test file.
* Move tests for legacy API to bottom of file. 
* Return `code` and `metadata` from `transform`; future iteration will remove use of `runtimeInjection` option from tests.
* Use OSS default imports and options.
* Imports are updated to be `import * as stylex from '@stylexjs/stylex'` (except legacy tests).
* Tests run using cjs modules by default.
* Add missing tests for dynamic styles.
* Tests for use with pseudo-class, pseudo-element, and queries.
=> [babel-plugin] Refactor stylex-transform-create-test.js

packages/babel-plugin/__tests__/transform-create-test.js, packages/babel-plugin/src/visitors/stylex-create/index.js
Pseudo elements not working in dynamic styles because we're setting `inherits: false`, see [978](https://github.com/facebook/stylex/issues/978)
Fixes [978](https://github.com/facebook/stylex/issues/978)
Ran on tests added in https://github.com/facebook/stylex/pull/977
Before:
After
Value is now set correctly
=> fix: fix pseudo elements in dynamic styles

packages/style-value-parser/src/at-queries-from-tokens/__tests__/media-query-transform-test.js, packages/style-value-parser/src/at-queries-from-tokens/media-query-transform.js, packages/style-value-parser/src/at-queries-from-tokens/media-query.js
create media query transformer to ensure “last query wins” logic
Now that we have a usable media query parser in https://github.com/facebook/stylex/pull/743, we can finally implement last media query wins logic. 
High level approach: traverse through styles, search for media queries, do two passes at each node - one to build up a list of negations for each query, and another to apply the negation. 
1. traverse nested styles with dfs
- dfs to find all nested media queries
- extract and flatten all media queries per into list for easier transformation
2. iterate media queries in reverse order
- loop through the extracted media queries from last to first 
3. accumulate negations
-backwards, for single pass
-  build up a list of negations from previous queries during reverse iteration
- apply …
=> feat: create media query transformer to ensure last query wins

packages/stylex/src/StyleXTypes.js
The Flow team is looking into killing `$Diff` now that Omit exists for a long time. This PR replaces the final `$Diff` in `StyleXTypes` with `Omit`. This was previously replaced from `$Rest` in #976 because some internal code is relying on weird behavior of `$Diff`, but they have been taken care of now so we can move away from it.
Close #994
=> Replace $Diff in StyleXTypes

packages/babel-plugin/__tests__/legacy/transform-logical-properties-test.js, packages/babel-plugin/__tests__/legacy/transform-logical-values-test.js, packages/babel-plugin/__tests__/transform-polyfills-test.js
Move tests for all CSS polyfills into 'transform-polyfills'. Snapshot the metadata of each transform.
The logical property/value tests are preserved in the `legacy` test directory for now. Almost all these tests are no longer needed, as there is no polyfill transform applied.
=> [babel-plugin] Refactor transform-polyfills-test

package-lock.json, packages/babel-plugin/__tests__/stylex-transform-define-consts-test.js, packages/babel-plugin/src/index.js, packages/babel-plugin/src/utils/state-manager.js, packages/babel-plugin/src/visitors/imports.js, packages/babel-plugin/src/visitors/stylex-define-consts.js, packages/shared/__tests__/stylex-define-consts-test.js, packages/shared/src/common-types.js, packages/shared/src/index.js, packages/shared/src/messages.js, packages/shared/src/stylex-consts-utils.js, packages/shared/src/stylex-define-consts.js, packages/stylex/src/StyleXTypes.js, packages/stylex/src/stylex.js
Adds support for new API `stylex.defineConsts` to inject constants into the css transform pipeline and replace `var(--token)` usage with raw values when processing rules
```js
// colors.stylex.js
import stylex from 'stylex'
export const colors = stylex.defineConsts({
red: '#ff0000',
green: '#00ff00',
})
// component.js
import stylex from 'stylex'
import { colors } from './colors.stylex'
box: {
color: colors.red,
backgroundColor: colors.green,
},
})
```
- accepts a JS object of constants  
- returns an object mapping unique hashed keys to `{ constKey, constVal }`  
- includes the hash as `key` to match css variable format
1. Walk ast and detect call to `stylex.defineConsts`
4. call `stylexDefineConsts` to convert obj to js output and metadata
5. replace the …
=> feat: create new `defineConsts` api

packages/babel-plugin/__tests__/transform-stylex-create-test.js, packages/babel-plugin/__tests__/transform-stylex-createTheme-test.js, packages/babel-plugin/__tests__/transform-stylex-defineConsts-test.js, packages/babel-plugin/__tests__/transform-stylex-defineVars-test.js, packages/babel-plugin/__tests__/validation-stylex-createTheme-test.js, packages/babel-plugin/src/visitors/parse-stylex-create-arg.js, packages/shared/src/preprocess-rules/PreRule.js, packages/shared/src/preprocess-rules/__tests__/PreRule-test.js, packages/shared/src/preprocess-rules/__tests__/flatten-raw-style-obj-test.js, packages/shared/src/stylex-keyframes.js, packages/shared/src/utils/__tests__/convert-to-className-test.js, packages/shared/src/utils/__tests__/split-css-value-test.js, packages/shared/src/utils/__tests__/transform-value-test.js, packages/shared/src/utils/convert-to-className.js, packages/shared/src/utils/generate-css-rule.js, packages/shared/src/utils/transform-value.js
A bit of housekeeping within the "shared" package.
* Add some test cases from "shared" to "babel-plugin".
* Colocate some "shared" tests with their internal modules.
=> [babel-plugin] Reorganize and move shared tests

packages/babel-plugin/__tests__/transform-stylex-create-test.js, packages/babel-plugin/src/shared/utils/__tests__/convert-to-className-test.js, packages/babel-plugin/src/shared/utils/convert-to-className.js
`firstThatWorks(a, b, c)` turns into an array of values that eventually gets passed into some shared `stylex.create` utils. 
```
borderColor: stylex.firstThatWorks('blue', 'var(--accent)')
```
When a property value array started with a CSS variable (e.g. ["var(--x)", "sticky"]), variableFallbacks called composeVars(...) and mistakenly spread its string result into an array. 
Resulting in broken output like:  broken output like 
```
".borderColor-xnybe8l{border-color:v;border-color:a;border-color:r;border-color:(;border-color:-;border-color:-;border-color:a;border-color:c;border-color:c;border-color:e;border-color:n;border-color:t;border-color:);border-color:blue}"
```
This fix wraps the composeVars result in an array to keep the return value consistent.
``` …
```
=> fix: fix first that works bug where last value is a variable

packages/style-value-parser/src/css-types-from-tokens/__tests__/calc-test.js, packages/style-value-parser/src/css-types-from-tokens/calc.js
This is a dependency to support media queries with `calc` and other uses
Two main changes:
- Added a new `group` node type to preserve user written parentheses in `calc()` expressions. We wrap all explicitly parenthesized expressions (like `(10 + 5)`) in a `{ type: 'group', expr }` node.
- Updated the parser to support nested groups and maintain correct order of operations
Implemented:
- toString()` method reconstructs the original `calc(...)` string exactly, including parentheses
- We can work on simplication afterwards (ie. collapsing stuff like parentheses implied by order of operation)
- Added test for round trip accuracy: `parse -> toString` returns the original string for all valid inputs
Known further improvements:
- Parser does not flag `calc(a+ b )` as invalid (flags other …
=> style-value-parser/feat: implement toString function in calc parser

packages/babel-plugin/src/shared/utils/__tests__/transform-value-test.js, packages/babel-plugin/src/shared/utils/transform-value.js
Fix the logic for automatically adding quotes around values for the `content` property, (often used within `::before` and `::after`)
The fix was to simply add `var(--` to the list of function strings the code uses to opt out of quotes today.
Fixes #1004
=> fix: invalid wrapping of variables as values for content

packages/style-value-parser/src/at-queries/__tests__/media-query-test.js, packages/style-value-parser/src/at-queries/media-query.js
Lots of edge cases to fix:
- ~~support `only` keyword~~
- ~~calc parsing broken with certain parentheses~~
- ~~implement `toString` in `Calc` parser class~~
- ~~duplicate not parsing broken~~
- ~~strange nested parentheses edge cases~~
- ~~refactor some width -> max-width logic~~
- ...to add as I test
Testing:
- so many tests! will refactor in a follow up PR
- added a number of invalid media query assertions
- i'm almost certain i'm missing some edge cases, but I think this covers 95+% of use cases and most of what we'll see practically. will continue to iterate
refs: [mdn media query docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries) 
[lightning css playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedi …
=> style-value-parser/feat: add parser support for more types of media queries

packages/babel-plugin/__tests__/transform-process-test.js
Adds some initial tests for the `stylexPlugin.processStylexRules` function that operates on extracted metadata. This takes the test coverage of `src/index.js` from 44% to 84%.
=> [babel-plugin] Add unit tests for processStylexRules

packages/stylex/rollup.config.mjs
Fixes a crash in the rollup config caused by __dirname being undefined in .mjs files. Added workaround using fileURLToPath(import.meta.url) to safely resolve paths
```
[!] TypeError: The "paths[0]" argument must be of type string. Received undefined
at new NodeError (node:internal/errors:405:5)
at validateString (node:internal/validators:162:11)
at Object.resolve (node:path:1115:7)
at file:///Users/mellyeliu/stylex/packages/stylex/rollup.config.mjs:32:24
```
=> stylex/fix: fix path resolve for config in ESM

packages/babel-plugin/__tests__/validation-stylex-create-test.js, packages/babel-plugin/__tests__/validation-stylex-createTheme-test.js, packages/babel-plugin/__tests__/validation-stylex-defineConsts-test.js, packages/babel-plugin/__tests__/validation-stylex-defineVars-test.js, packages/babel-plugin/__tests__/validation-stylex-keyframes-test.js, packages/babel-plugin/src/shared/messages.js, packages/babel-plugin/src/visitors/stylex-create-theme.js, packages/babel-plugin/src/visitors/stylex-create.js, packages/babel-plugin/src/visitors/stylex-define-consts.js, packages/babel-plugin/src/visitors/stylex-define-vars.js, packages/babel-plugin/src/visitors/stylex-keyframes.js
Fixes https://github.com/facebook/stylex/issues/1028
- Refactors hardcoded error strings into template functions for consistency and reuse across different APIs (previously many were incorrectly referencing `stylex.create()` calls
- Removes some unused error messages
=> babel-plugin/chore: convert static error messages to template functions

packages/stylex/src/types/StyleXCSSTypes.js
This PR adds flow types for CSS-based anchor positioning properties. Prevents the need to $FlowFixMe when using these properties.
I saw that @nmn currently has a PR up for supporting @position-try. This would also be useful for me internally in the short to medium term future.
=> [chore] add flow types for anchor positioning css properties to StyleXCSSTypes.js

packages/babel-plugin/jest.config.js, packages/babel-plugin/package.json, packages/eslint-plugin/jest.config.js, packages/eslint-plugin/package.json, packages/style-value-parser/jest.config.js, packages/style-value-parser/package.json, packages/stylex/jest.config.js, packages/stylex/package.json
Help prevent regressions to code coverage for babel-plugin, eslint-plugin, style-value-parser, and stylex packages. The thresholds for packages with low coverage should be increased as coverage improves.
=> Add jest coverage thresholds to packages

packages/style-value-parser/src/at-queries/__tests__/media-query-test.js, packages/style-value-parser/src/at-queries/media-query.js
Refactor tests and gauge spec gaps. I think we support pretty much all the query types we'd expect to see in internal now, and can start using it in the compiler and linter
- Mostly rearranging tests
- Added new tests for double inequalities, normalization tests, etc
Not supported: 
- niche keywords like horizontal-viewport-segments, vertical-viewport-segments, environment-blending, video-* media features, dynamic-range, prefers-reduced-data
=> style-value-parser/chore: refactor media query tests

packages/docs/docs/api/configuration/eslint-plugin.mdx, packages/eslint-plugin/__tests__/stylex-sort-keys-test.js, packages/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/eslint-plugin/src/stylex-sort-keys.js, packages/eslint-plugin/src/stylex-valid-styles.js
Rebase of https://github.com/facebook/stylex/pull/569
=> [eslint-plugin] Support importSources object syntax in validImports

package-lock.json, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-create-test.js, packages/@stylexjs/babel-plugin/src/shared/stylex-create.js
Nested pseudo-classes have a pre-determined order, which means 2 different ways of authoring a style were producing the same CSS. But the compiler was adding a duplicate class name into the compiled style object.
Co-authored-by: jeongminsang <jong0364@gmail.com>
Fix #1001
=> [babel-plugin] Remove duplicate className for nested pseudo-classes

packages/@stylexjs/babel-plugin/__tests__/transform-import-export-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-positionTry-test.js, packages/@stylexjs/babel-plugin/__tests__/validation-import-export-test.js, packages/@stylexjs/babel-plugin/src/index.js, packages/@stylexjs/babel-plugin/src/shared/index.js, packages/@stylexjs/babel-plugin/src/shared/messages.js, packages/@stylexjs/babel-plugin/src/shared/stylex-position-try.js, packages/@stylexjs/babel-plugin/src/utils/state-manager.js, packages/@stylexjs/babel-plugin/src/visitors/imports.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-create-theme.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-create.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-define-vars.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-keyframes.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-position-try.js, packages/@stylexjs/stylex/__tests__/inject-test.js, packages/@stylexjs/stylex/__tests__/stylex-test.js, packages/@stylexjs/stylex/src/stylex.js, packages/@stylexjs/stylex/src/types/StyleXCSSTypes.js, packages/@stylexjs/stylex/src/types/StyleXTypes.d.ts, packages/@stylexjs/stylex/src/types/StyleXTypes.js
Adds a new `stylex.positionTry` API that lets you create `@position-try` rules.
It works pretty much just like `stylex.keyframes`.
Fixes #1003 
New test file is included which shows the new feature working.
=> feat: Add new stylex.positionTry for @property-try declarations

examples/example-nextjs/typetests/typetests.ts, packages/@stylexjs/babel-plugin/__tests__/legacy/stylex-transform-call-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-props-test.js, packages/@stylexjs/eslint-plugin/README.md, packages/@stylexjs/eslint-plugin/__tests__/stylex-no-legacy-contextual-styles-test.js, packages/@stylexjs/eslint-plugin/src/index.js, packages/@stylexjs/eslint-plugin/src/stylex-no-legacy-contextual-styles.js, packages/@stylexjs/stylex/flow-tests/stylex-create.js.flow, packages/docs/blog/2025-04-10-Release-v0.12.0.mdx, packages/docs/docs/learn/04-styling-ui/01-defining-styles.mdx, packages/docs/docs/learn/06-recipes/03-descendant styles.mdx
Defining new term 'contextual styles' for nested conditions like pseudoclasses and at-rules
```
import * as stylex from '@stylexjs/stylex';
base: {
width: {
default: 800,
'@media (max-width: 800px)': '100%',
'@media (min-width: 1540px)': 1366,
},
},
});
```
and a small naming tweak to `no-legacy-media-queries` linter since this rule captures both media queries and pseudo classes
=> [docs] introduce 'contextual styles' term

packages/docs/docs/learn/04-styling-ui/02-using-styles.mdx
Removes outdated reference to `stylex.attrs`, simplifies the language, and visually de-clutters the page.
=> [docs] Improve "Using styles" page

package-lock.json, packages/@stylexjs/babel-plugin/__tests__/__fixtures__/constants.stylex.js, packages/@stylexjs/babel-plugin/__tests__/transform-process-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-defineConsts-test.js, packages/@stylexjs/babel-plugin/jest.config.js, packages/@stylexjs/babel-plugin/src/shared/preprocess-rules/PreRule.js, packages/@stylexjs/babel-plugin/src/shared/preprocess-rules/basic-validation.js, packages/@stylexjs/babel-plugin/src/shared/utils/__tests__/convert-to-className-test.js, packages/@stylexjs/babel-plugin/src/shared/utils/convert-to-className.js, packages/@stylexjs/babel-plugin/src/shared/utils/generate-css-rule.js
https://github.com/facebook/stylex/pull/944 only supports inlining values. Need to properly wrap css rules with media queries, @supports, @container etc
1. We were replacing var(--hash) in the final css ltr strings inside our main babel transform (in `processStylexRules`), but that only touches the output css and doesn’t affect how `stylex-create` wraps declarations
2. `stylex-create` walks the raw style object and builds the ltr strings by wrapping rules in @media {...} based on object keys, but we never looked for var(...) keys there—so any media constants were ignored
4. this diff patches the part that builds the `PreRule`s to detect key segments matching var(--hash) and emits them as literal var(--hash){...} wrappers as a placeholder. once `processStylexRules` runs (where we have the …
=> [babel-plugin] support at-rules in defineConsts

packages/@stylexjs/stylex/src/types/StyleXTypes.d.ts, packages/@stylexjs/stylex/src/types/VarTypes.js
Made some changes to the Flow types so that the generated Typescript types are valid.
Also made some changes to a typescript `.d.ts` file to make it valid.
Fixes #969 
Some type constraints loosened up so various `stylex.types.*` classes would have the same constraints to make things work correctly in Typescript.
This doesn't actually make the types less strict because the type constraints on the actual functions are unchanged.
=> fix: Typescript type fixes for themes and types functions

packages/@stylexjs/babel-plugin/__tests__/transform-stylex-createTheme-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-defineVars-test.js, packages/@stylexjs/babel-plugin/src/utils/__tests__/state-manager-test.js, packages/@stylexjs/babel-plugin/src/utils/state-manager.js, packages/@stylexjs/rollup-plugin/__tests__/index-test.js, packages/@stylexjs/rollup-plugin/src/index.js, packages/docs/docs/api/configuration/babel-plugin.mdx
We want to discourage use of runtimeInjection in all scenarios, and will no longer enable it by default when 'dev' is true.
=> [babel-plugin] Don't auto-enable runtimeInjection option for dev option

packages/@stylexjs/postcss-plugin/README.md, packages/@stylexjs/postcss-plugin/src/builder.js, packages/@stylexjs/postcss-plugin/src/bundler.js, packages/@stylexjs/postcss-plugin/src/index.js, packages/docs/docs/api/configuration/postcss-plugin.mdx
This PR adds `importSources` option to be configurable in order to allow reusing the plugin for react-strict-dom, and sets `platform: "web"` as babel.caller as required by RSD babel preset.
react-strict-dom currently relies on a community-maintained package [postcss-react-strict-dom](https://github.com/javascripter/postcss-react-strict-dom) that I maintain to extract styles statically.
I'm intending to upstream the PostCSS plugin to RSD but [the initial attempt](https://github.com/facebook/react-strict-dom/pull/282) required forking the plugin instead of simply re-exporting the plugin with pre-defined config because `shouldTransform()` function currently  skips files that do not match `stylex`. This leads to additional maintenance burden and is not ideal.
By allowing `importSources` to be …
=> [postcss-plugin] Implement custom importSources for React Strict DOM compatibility

packages/@stylexjs/postcss-plugin/src/bundler.js
Using the `{ from, as }` object form in importSources caused a runtime error due to incorrect .includes usage in [Previous PR](https://github.com/facebook/stylex/pull/1063). This fix ensures both string and object forms are handled properly in shouldTransform.
https://github.com/facebook/stylex/pull/1063
In main branch, move to the example app
```bash
cd examples/example-nextjs
```
Using the object syntax throws when running `npm run example:dev`:
```javascript
importSources: [
{
// Note:Just enough config to reproduce the error, not actually a proper config for stylex
from: '@stylexjs/stylex',
as: 'create',
},
],
```
Switch to this branch and now it does not throw and renders correctly.
=> [postcss-plugin] Fix importSource object syntax not working properly

package-lock.json, packages/@stylexjs/postcss-plugin/__tests__/__fixtures__/.babelrc.js, packages/@stylexjs/postcss-plugin/__tests__/__fixtures__/.babelrc.json, packages/@stylexjs/postcss-plugin/__tests__/__fixtures__/import-sources-object.js, packages/@stylexjs/postcss-plugin/__tests__/__fixtures__/import-sources-string.js, packages/@stylexjs/postcss-plugin/__tests__/__fixtures__/styles-second.js, packages/@stylexjs/postcss-plugin/__tests__/__fixtures__/styles.js, packages/@stylexjs/postcss-plugin/__tests__/index-test.js, packages/@stylexjs/postcss-plugin/jest.config.js, packages/@stylexjs/postcss-plugin/package.json, packages/@stylexjs/postcss-plugin/src/plugin.js
This PR adds tests for `@stylexjs/postcss-plugin` as per  https://github.com/facebook/stylex/pull/1065#pullrequestreview-2848354763
Fixes https://github.com/facebook/stylex/pull/1065#pullrequestreview-2848354763
1. Confirmed that tests pass in this branch, and if we revert the fix from [the previous PR](https://github.com/facebook/stylex/pull/1065), tests fail as expected.
2.
Checked `examples/example-nextjs` still renders correctly in this branch
=> [postcss-plugin] Add unit tests

examples/example-cli/package.json, examples/example-esbuild/package.json, examples/example-nextjs/package.json, examples/example-rollup/package.json, examples/example-webpack/package.json, package-lock.json, packages/@stylexjs/babel-plugin/package.json, packages/@stylexjs/cli/package.json, packages/@stylexjs/eslint-plugin/package.json, packages/@stylexjs/postcss-plugin/package.json, packages/@stylexjs/rollup-plugin/package.json, packages/@stylexjs/stylex/package.json, packages/benchmarks/package.json, packages/docs/package.json, packages/scripts/package.json, packages/style-value-parser/package.json
```
$ npm run release -- -v 0.13.0
```
since https://github.com/facebook/stylex/issues/1034 is wrapped up
will add release notes in separate pr
=> [release] v0.13.0

packages/@stylexjs/stylex/src/stylex.js
These types are currently used by React Strict DOM
Needed for https://github.com/facebook/react-strict-dom/pull/311
=> [stylex] Add types to exports

packages/@stylexjs/babel-plugin/__tests__/transform-stylex-viewTransitionClass-test.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-view-transition-class.js
In https://github.com/facebook/stylex/pull/1078 I added an initial implementation of `viewTransitionClass` and when I was doing some additional manual exploration I noticed that using the `keyframes` API inline in the `viewTransitionClass` object wasn't working so this diff resolves that by adding support. This is a small thing but can really help keep the view transition configuration (relatively) consise.
Added unit test covering the scenario and it is passing.
=> feat: allow inline keyframe expressions inside viewTransitionClass

.github/workflows/typos.toml
Too many false positives on inline snapshots
=> Exclude all test files from 'typos' workflow

packages/@stylexjs/eslint-plugin/README.md, packages/@stylexjs/eslint-plugin/__tests__/stylex-enforce-extension-test.js, packages/@stylexjs/eslint-plugin/__tests__/stylex-no-legacy-contextual-styles-test.js, packages/@stylexjs/eslint-plugin/__tests__/stylex-no-unused-test.js, packages/@stylexjs/eslint-plugin/__tests__/stylex-sort-keys-test.js, packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/@stylexjs/eslint-plugin/src/stylex-enforce-extension.js, packages/@stylexjs/eslint-plugin/src/stylex-no-legacy-contextual-styles.js, packages/@stylexjs/eslint-plugin/src/stylex-no-unused.js, packages/@stylexjs/eslint-plugin/src/stylex-sort-keys.js, packages/@stylexjs/eslint-plugin/src/stylex-valid-shorthands.js, packages/@stylexjs/eslint-plugin/src/utils/createImportTracker.js, packages/docs/docs/api/configuration/eslint-plugin.mdx
Continuing on https://github.com/facebook/stylex/pull/1039, this PR adds `validImports` option to all eslint rules with support for both the string and object syntax uniformly, for RSD compatibility and other custom aliases.
I've also updated API docs and the README to document the options. I expect documentation rework to be made in another PR (pending https://github.com/facebook/stylex/issues/1057) so made the change minimal.
Main changes:
- added `validImports` option to all rules
- refactored the import name tracking logic to `src/utils/createImportTracker.js` to reduce duplication
- added unit tests to test for custom aliases
- documented changes
Fixes https://github.com/facebook/stylex/issues/1056
I ran the following tests locally and confirmed existing and new tests are passing: …
=> [eslint-plugin] support validImports options for all rules

packages/@stylexjs/babel-plugin/__tests__/transform-stylex-createTheme-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-defineVars-test.js
Unit tests to better capture the way that theming currently works in StyleX.
Background:
* [#630](https://github.com/facebook/stylex/issues/601) describes how StyleX theming used to work, and that it wasn't matching user expectations.
* A solution was found to match expectations.
* [5f14ff58](https://github.com/facebook/stylex/commit/5f14ff580127769b7d6c315eed4e0a090230418a) is a patch that made a change to how StyleX theming works.
* I recently noticed in the React Strict DOM example app that StyleX-based theming regressed on web.
Patch:
* Make sure we capture the complete metadata in the createTheme tests. Previously, we did not have visibility into all the CSS rules generated.
* Add extra tests to capture scenarios where multiple variables and themes are created across files. These …
=> [babel-plugin] Improve createTheme and defineVars tests

packages/@stylexjs/babel-plugin/README.md, packages/@stylexjs/babel-plugin/src/shared/README.md, packages/@stylexjs/eslint-plugin/README.md, packages/@stylexjs/stylex/README.md, packages/docs/blog/2023-12-29-Release-v0.4.1.md, packages/docs/blog/2024-01-25-Release-v0.5.0.md, packages/docs/blog/2024-04-16-Release-v0.6.1.mdx, packages/docs/blog/2024-06-25-Release-v0.7.0.mdx, packages/docs/blog/2024-10-06-Release-v0.8.0.mdx, packages/docs/blog/2024-11-01-Release-v0.9.3.mdx, packages/docs/blog/2025-02-27-Release-v0.11.0.mdx, packages/docs/docs/api/configuration/babel-plugin.mdx, packages/docs/docs/api/javascript/defineConsts.mdx, packages/docs/docs/api/javascript/defineVars.mdx, packages/docs/docs/api/javascript/types.mdx, packages/docs/docs/api/types/Theme.mdx, packages/docs/docs/api/types/VarGroup.mdx, packages/docs/docs/learn/02-thinking-in-stylex.mdx, packages/docs/docs/learn/04-styling-ui/01-defining-styles.mdx, packages/docs/docs/learn/04-styling-ui/02-using-styles.mdx, packages/docs/docs/learn/05-theming/01-defining-variables.mdx, packages/docs/docs/learn/05-theming/02-using-variables.mdx, packages/docs/docs/learn/05-theming/03-creating-themes.mdx, packages/docs/docs/learn/05-theming/04-variable-types.mdx, packages/docs/docs/learn/06-recipes/03-descendant styles.mdx, packages/docs/docs/learn/06-recipes/04-reset-themes.mdx
Left a few instances in titles or headers where it seemed appropriate, but otherwise renaming across docs for consistency
=> [docs] rename `stylex.*` functions to `*` in docs and READMEs

packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/@stylexjs/eslint-plugin/src/stylex-valid-styles.js, packages/docs/components/YouTube.js
Adds autofix for remaning nonstandard properties (borderRadius, start/end) and nonstandard style values (for `float` and `clear`) 
We will need to test sync this to see volume of lint errors, then see if @vincentriemer's CodemodService can run on this without needing to land the sync itself
=> [eslint-plugin] add autofix for remaining nonstandard properties

packages/@stylexjs/stylex/src/types/StyleXCSSTypes.js, packages/@stylexjs/stylex/src/types/StyleXTypes.d.ts, packages/@stylexjs/stylex/src/types/StyleXTypes.js
Currently at type level (at least in TypeScript, I'm not fully sure about Flow so if it impacts it in some way - I'm open for any feedback 😃) you can't use vars created by `styles.defineVars` inside of variable typed as `StyleXStyles`(which is useful for e.g. component props). 
Example (adjusted code from `examples/example-nextjs/typetests/theming`):
```ts
export const ButtonTokens = stylex.defineVars({
bgColor: stylex.types.color('red'),
color: 'currentcolor',
height: 'var(--button-height-medium)',
opacity: '1',
});
```
in other file:
```tax
test1: {
padding: 4,
color: ButtonTokens.bgColor,
backgroundColor: `color-mix(in oklch, ${ButtonTokens.bgColor}, 'white')`,
},
});
const test: stylex.StyleXStyles = styles.test1;
```
This causes TypeScript error:
This …
=> fix: allow stylex.types.* in StyleXStyles by resolving CSSType to underlying type

packages/@stylexjs/babel-plugin/__tests__/legacy/stylex-transform-legacy-shorthands-test.js, packages/@stylexjs/babel-plugin/src/shared/preprocess-rules/legacy-expand-shorthands.js
This is a longstanding bug for `marginInline`, `marginBlock`, `paddingInline`, `paddingBlock` (https://github.com/facebook/stylex/issues/1091). I'm guessing it's an oversight because the rest of the shorthands (`margin`, `padding`, `gap`, etc.) are handled with `splitValue`. 
Currently, we don't split or handle the values passed to any of these properties. The `valid-shorthands` linter discourages them anyway, but internally it's not enabled everywhere and not strictly enforced.
```
paddingBlock: "5px 10px" ->
_inject2(".x4tyy86{padding-top:5px 10px}", 4000);
_inject2(".xr7q0qe{padding-bottom:5px 10px}", 4000);
```
This PR handles these values appropriately:
```
paddingBlock: "5px 10px" ->
_inject2(".x4tyy86{padding-top:5px}", 4000);
_inject2(".xr7q0qe{padding-bottom:10px}", 4000);
```
=> [babel-plugin][legacy] fix expansion for marginInline, paddingInline, etc

tools/README.md, tools/npm/release.js
We can't do everything in one command because we can't push commits directly to `main`. And the GitHub PR UI creates a new commit on merge, which means tags have to be added to the post-merge commit on `main`.
=> Update npm-release documentation

packages/docs/docs/learn/06-recipes/03-descendant styles.mdx
The component on line 77 is incorrectly titled `ParentWithHover`, the same as the component on line 54. It looks like this was probably a copy error. But the component on the 77 is actually the descendant of the parent component on line 54.
This is meant to clarify the documentation. The mislabelling makes the example confusing
=> Update 03-descendant styles.mdx

packages/docs/docs/learn/03-installation.mdx
Fixed incorrect ESLint rule severity syntax in the installation documentation (`packages/docs/docs/learn/03-installation.mdx`).
**Changes:**
- Changed `"warning"` to `"warn"` for `@stylexjs/sort-keys` rule
- Changed `"warning"` to `"warn"` for `@stylexjs/valid-shorthands` rule
**Motivation:**
The current documentation uses `"warning"` as ESLint rule severity, but this is not a valid ESLint rule level. According to [ESLint's official documentation](https://eslint.org/docs/latest/use/configure/rules#rule-severities), the only valid rule severity levels are:
- `"off"` or `0` - turn the rule off
- `"warn"` or `1` - turn the rule on as a warning (doesn't affect exit code)
- `"error"` or `2` - turn the rule on as an error (exit code is 1 when triggered)
This causes ESLint configuration …
=> docs: Fix ESLint rule severity syntax in installation guide

packages/@stylexjs/babel-plugin/__tests__/evaluation-import-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-import-export-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-process-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-createTheme-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-defineVars-test.js, packages/@stylexjs/babel-plugin/__tests__/validation-stylex-createTheme-test.js, packages/@stylexjs/babel-plugin/src/shared/stylex-create-theme.js, packages/@stylexjs/babel-plugin/src/shared/stylex-define-consts.js, packages/@stylexjs/babel-plugin/src/shared/stylex-define-vars.js, packages/@stylexjs/babel-plugin/src/utils/evaluate-path.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-create-theme.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-define-consts.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-define-vars.js
`defineVars` and `defineConsts` make use of a variable called `themeName`, which is actually a unique identifier for a group of variables (referred to as a `VarGroup` in the docs). This identifier is a hash generated from the var/const exported name and the file path. 
Renamed `themeName` to `varGroupHash` and the filename/export reference to `exportId` across `defineVars` and `defineConsts`, to better reflect their actual roles, as the naming has been hard to follow
=> [babel-plugin] refactor defineVars and defineConsts var naming

packages/@stylexjs/babel-plugin/__tests__/legacy/transform-logical-values-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-process-test.js, packages/@stylexjs/babel-plugin/src/shared/common-types.js, packages/@stylexjs/babel-plugin/src/shared/physical-rtl/generate-rtl.js, packages/@stylexjs/babel-plugin/src/shared/utils/default-options.js, packages/@stylexjs/babel-plugin/src/utils/state-manager.js
Cartesian coordinates (x,y) and cardinal directions (N,E,S,W) should not be flipped for RTL writing directions. This behavior is neither part of the W3C standards nor common sense.
The behavior is preserved (but disabled by default) with a new feature flag - enableLegacyLogicalValues - while Meta migrates internal code off this behavior.
Fix #1120
=> Remove legacy RTL flipping of boxShadow, cursor, textShadow values

packages/@stylexjs/eslint-plugin/src/rules/isNumber.js, packages/@stylexjs/eslint-plugin/src/stylex-valid-styles.js
Fixes #1134
- `isNumber`  previously returned `undefined` due to an improper ternary check, causing them to always pass. rewrote using basic if/else for readability
- `isMathCall` logic was error prone and overly strict, required all Math.*() arguments to be recursively valid numbers, false negatives and circular dependencies
- Meaning every length css property (or any property with an `isNumber` check) was always valid as per the linter
- Fixed logic to correctly return a `RuleResponse` when a value is invalid.
- Also allowed `MemberExpression` and `CallExpression` nodes to broadly allow functions/vars as valid number values (we could make this stricter, but they're not reliably statically analyzable, and I suspect it'll add a ton of volume to the internal eslint errors, and it's still …
=> [eslint-plugin] fix isNumber utils and isMathCall utils

packages/@stylexjs/babel-plugin/__tests__/legacy/stylex-transform-legacy-shorthands-test.js, packages/@stylexjs/babel-plugin/src/shared/preprocess-rules/legacy-expand-shorthands.js
fixes https://github.com/facebook/stylex/issues/1149 
in https://github.com/facebook/stylex/pull/1083 i missed expanding paddingLeft into logical inline styles, so they never get mapped to paddingLeft/paddingRight in `generate-ltr` / `generate-rtl`
=> [babel-plugin] fix expansion for paddingLeft for legacy-expand-shorthands

packages/@stylexjs/babel-plugin/__tests__/evaluation-import-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-process-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-create-test.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-create.js
Rewrite for dynamic styles handling that is sort of long overdue. previous approach is quite imprecise and brittle in the way strings are built up. this has a few changes to the existing behaviour:
- old version mapped classNames back to expressions via `origClassPaths` dict (kind of brittle reverse look up of stringified path arrays that were pretty broken - according to the tests, never fully worked) (causing issues like https://github.com/facebook/stylex/issues/1146)
- new version just inspects the metadata directly to build a list of style keys by determining which styles are expressions instead of static
- also rebuilds the string from scratch with conditional logic instead of mutating in place strangely
Testing:
- tested in `example-nextjs`
- confirmed
- no width omitted
- null …
=> [babel-plugin] rewrite dynamic styles construction 

packages/@stylexjs/babel-plugin/__tests__/transform-stylex-defineConsts-test.js, packages/docs/docs/api/javascript/defineConsts.mdx
Let's add some documentation for known fail cases for `defineConsts` as I circle around to them
See https://github.com/facebook/stylex/issues/1154, https://github.com/facebook/stylex/issues/1162
=> [babel-plugin] document fail cases for defineConsts

packages/docs/babel.config.js, packages/docs/docs/api/javascript/defineVars.mdx, packages/docs/docs/learn/05-theming/01-defining-variables.mdx, packages/docs/docs/learn/05-theming/03-creating-themes.mdx, packages/docs/docs/learn/05-theming/04-variable-types.mdx
There were some docs about theming that were outdated and incorrect. Thanks to @BMCwebdev for bringing it to our attention in https://github.com/facebook/stylex/discussions/947
I updated that and clarified some sentences that could be misleading.
=> [docs] Update outdated or misleading theming docs

packages/@stylexjs/babel-plugin/__tests__/transform-stylex-create-test.js, packages/@stylexjs/babel-plugin/src/shared/common-types.js, packages/@stylexjs/babel-plugin/src/shared/preprocess-rules/flatten-raw-style-obj.js, packages/@stylexjs/babel-plugin/src/shared/utils/default-options.js, packages/@stylexjs/babel-plugin/src/utils/state-manager.js, packages/style-value-parser/src/at-queries/__tests__/media-query-transform-test.js, packages/style-value-parser/src/at-queries/__tests__/parse-media-query-test.js, packages/style-value-parser/src/at-queries/media-query.js
Updated mergeIntervalsForAnd to properly merge and simplify ranges for min-width / max-width pairs:
- build numeric intervals for each dimension (width/height). it collects all the lower and upper bounds from the rules and determines the tightest range:
- for min-width it takes the largest lower bound
- for max-width it takes the smallest upper bound
Added handling for the special case of overlapping queries inside an outer range. If there's a gap in the valid intervals, the function now splits the outer range into valid disjoint intervals on either side of the hole.
- if the hole fully overlaps the lower or upper side of the outer range, we drop the empty side
- if both sides are valid, we return them as an or group so the final query represents both disjoint intervals
- if only one side …
=> [style-value-parser] process disjoint, intersecting, and subset ranges in media queries

CHANGELOG.md, examples/example-cli/package.json, examples/example-esbuild/package.json, examples/example-nextjs/package.json, examples/example-rollup/package.json, examples/example-webpack/package.json, package-lock.json, packages/@stylexjs/babel-plugin/package.json, packages/@stylexjs/cli/package.json, packages/@stylexjs/eslint-plugin/package.json, packages/@stylexjs/postcss-plugin/package.json, packages/@stylexjs/rollup-plugin/package.json, packages/@stylexjs/stylex/package.json, packages/benchmarks/package.json, packages/docs/package.json, packages/scripts/package.json, packages/style-value-parser/package.json, packages/typescript-tests/package.json
- Hoist stylex.create and static className objects to the top level for support inside functions
- Mark `style-value-parser` as public
Will be easier/more maintainable than inlining across packages
=> [release] v0.15.1

packages/@stylexjs/babel-plugin/__tests__/evaluation-import-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-process-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-create-test.js, packages/@stylexjs/babel-plugin/src/visitors/__tests__/parse-stylex-create-arg-test.js, packages/@stylexjs/babel-plugin/src/visitors/parse-stylex-create-arg.js
This is a simple fix for a bug that Figma encountered. The CSS custom properties that StyleX generates for dynamic styles can easily collide with existing CSS vars during a code migration. Prefixing them with `x-` makes that much less likely.
=> [babel-plugin] Reduce chances of dynamic variable name collisions

packages/@stylexjs/babel-plugin/__tests__/transform-stylex-create-test.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-create.js
Bug introduced in https://github.com/facebook/stylex/pull/1153, missing space concat for contextual styles. When we are constructing a key with multiple classnames (contextual style) we need to add a space suffix to each classname except the last. Previous logic included this `const suffix = index === classList.length - 1 ? '' : ' ';` but was not ported over.
Fixes https://github.com/facebook/stylex/issues/1191
=> [babel-plugin] fix classname construction for dynamic contextual styles

packages/@stylexjs/babel-plugin/__tests__/legacy/transform-pre-plugin-test.js, packages/@stylexjs/babel-plugin/__tests__/transform-stylex-props-test.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-props.js
Optimizes simple cases of `{...stylex.props()}` in JSX to avoid the overhead of extra object creation that the Babel jsx transform introduces.
This simple input:
```
<div {...stylex.props(styles.text)}>
hi
</div>;
```
was being transformed into:
```
React.jsx(
"div",
babelHelpers["extends"](
{className: "xw7yly9"},
{children: "hi"}
)
);
```
To prevent creating temporary objects, and dynamically iterating and merging props, this patch transforms the input to static object
```
React.jsx(
"div",
{
className: "xw7yly9",
children: "hi"
}
);
```
It also adds a warning in the case where a `className` prop is found after the `{...stylex.props}`.
At the moment we only have 2 or 3 props that `stylex.props` returns, but the code is written in a generalized way so it should still work if that changes …
=> [babel-plugin] Optimize precomputed props call in JSX

packages/docs/docs/learn/07-ecosystem.mdx
This PR changes the documentation of third-party bundler integrations.
According to vite-plugin-stylex-dev's [document](https://github.com/nonzzz/vite-plugin-stylex), it is no longer maintained, and the author encourage us to use stylex-extend by the same author instead.
=> docs: replace vite-plugin-stylex-dev with stylex-extend

packages/@stylexjs/babel-plugin/src/utils/state-manager.js, packages/@stylexjs/eslint-plugin/src/rules/isStylexResolvedVarsToken.js, packages/@stylexjs/eslint-plugin/src/stylex-valid-styles.js
It's a common case for users to write their own transforms that do special processing to inline, modify, or pre-resolve constants. Because the StyleX linter and compiler run on pre-transformed JS, the linter will flag these imports and cause unnecessary noise for developers.
- This is a quick patch to unblock an internal launch and the specific approach can be revisited as needed.
- Adds a new file extension `.transformed` (for files with exports that are pre-resolved before StyleX runs) with similar handling to `.stylex` (for files with `defineConsts` and `defineVars` exports) allowing them to be used in `stylex.create` calls
- Some naming cleanup as `.stylex` marks both `defineConsts` and `defineVars` anyway
- Compiler behavior is unchanged: variables unresolved at build time will still …
=> [babel-plugin] create new `.transformed` file extension for pre-resolved variables and constants

packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/@stylexjs/eslint-plugin/src/reference/cssProperties.js
Small patch for unitless '0' strings to allow `margin: '0'` syntax
https://developer.mozilla.org/en-US/docs/Web/CSS/length#syntax
=> [eslint-plugin] allow '0' values for length properties

packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/@stylexjs/eslint-plugin/src/rules/isNumber.js, packages/@stylexjs/eslint-plugin/src/stylex-valid-styles.js, packages/@stylexjs/eslint-plugin/src/utils/makeVariableCheckingRule.js
The `isNumber` lint check was incorrectly flagging identifiers for constants declared in the same file. We generally allow them in place of number literals as Babel handles the static evaluation of these bindings.
The rule now resolves scope correctly so that same-file `const` identifiers initialized with numbers can be used within arithmetic expressions and pass without error.
Within the `isNumber` check
- resolve math expressions down to both sides as before
- use `getScope` to determine whether any identifiers are declared within the file
=> [eslint-plugin] allow local resolved constants in valid-styles number checks

packages/@stylexjs/babel-plugin/__tests__/transform-process-test.js, packages/@stylexjs/babel-plugin/src/index.js, packages/@stylexjs/babel-plugin/src/shared/common-types.js, packages/@stylexjs/babel-plugin/src/shared/utils/default-options.js, packages/@stylexjs/babel-plugin/src/utils/state-manager.js, packages/@stylexjs/cli/src/transform.js, packages/@stylexjs/postcss-plugin/src/builder.js, packages/@stylexjs/postcss-plugin/src/bundler.js, packages/@stylexjs/postcss-plugin/src/plugin.js, packages/@stylexjs/rollup-plugin/src/index.js, packages/docs/scripts/make-stylex-sheet.js
To enable us to use `processStylexRules` internally, let's port some of the special handling we do in Haste to the OSS implementation. We only need to apply this to the legacy style resolution, which is only used inside of Meta. It's more performant to move this logic here than to do additional post processing again after grabbing the outputted rules
This includes:
- Adding generalizable config to `processStylexRules` to replace the previous useLayers param (backwards compatible via boolean check) 
- Adding `/* @ltr begin */` comments
- The logical style polyfills that generate these comments are being removed, but we need to keep inline `float` polyfills for a while longer, and for legacy browsers
- Adding `theme` specificity bumps globally. We do this to bump the specificity of …
=> [babel-plugin] support configurations within `processStylexRules`

packages/@stylexjs/babel-plugin/__tests__/transform-process-test.js, packages/@stylexjs/babel-plugin/src/index.js
Adds support for overriding `defineConsts` variables that are set to `var(--*)` references when used in `stylex.create` to support Figma migration to StyleX.
- Previously, constants defined as CSS variable indirections could not be overridden in component create calls because the key reference was not changed. 
- We now map the `--consthash` value to the CSS variable name (`--background-color` in the example)
- We replace `var(--hash)` with the `constValue` as always
- We replace `--hash:` with the extracted `--varName:` for both simple variables `var(--varName)` and fallback variables `var(--varName, fallback)`. The `:` is to ensure we're replacing keys and not other edge cases that interfere with debug classnames 
- Constants now behave more like passthroughs: if the referenced CSS …
=> [babel-plugin] support `defineConsts` var() overrides

packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-styles-test.js, packages/@stylexjs/eslint-plugin/src/stylex-valid-styles.js
Add an option `allowRawCSSVars` to `valid-styles` to allow styles to target raw CSS variables.
Fixes [#1226](https://github.com/facebook/stylex/issues/1226)
Simple test cases added and are passing.
=> [eslint-plugin] feat: add option to allow raw CSS variable overrides in valid-styles

packages/@stylexjs/babel-plugin/__tests__/transform-process-test.js, packages/@stylexjs/babel-plugin/src/index.d.ts, packages/@stylexjs/babel-plugin/src/index.js
Let's add a legacy config to disable layers and layers polyfill within `processStylexRules` so we can incrementally roll out CSS ordering changes internally. The only specificity difference between this implementation and the internal one is the secondary sort after rules are sorted by priority (alphabetical by classname vs alphabetical by style declaration
This helps unblock (1) `defineConsts` (2) fully shipping logical styles (3) further CSS normalization (4) media query grouping etc. 
This config should not be used by outside users.
=> [babel-plugin][legacy] add legacyDisableLayers configuration in processStylexRules

packages/@stylexjs/babel-plugin/__tests__/transform-stylex-props-test.js, packages/@stylexjs/babel-plugin/src/visitors/stylex-create.js
Hoisting `stylex.create` can today result in a bug when `stylex.props` is pre-compiled.
This is because we manually memoize various `stylex.create` definitions by name.
This is not safe when the definition isn't already top-level as the same constant in two different contexts can conflict with each other.
This PR disables memoization of `stylex.create` calls that are not at the top level. As of right now, this means that it results in fewer compile-time optimizations of `stylex.props()` calls, but it does fix the bug.
There is already work underway to optimize `stylex.props` pre-compilation that will re-introduce the intended optimizations.
Fixes #1252
=> [babel-plugin] Fix hoisiting stylex.create with duplicate names correctly 

packages/@stylexjs/babel-plugin/__tests__/transform-process-test.js, packages/@stylexjs/babel-plugin/src/index.js
Similar logic to https://github.com/facebook/stylex/pull/1244. Let's migrate to `processStylexRules` in steps. We use classnames alphanumeric sort internally, let's start with that to avoid visual regressions.
1. Rollout to `processStylexRules` with `useLegacyClassnamesSort: true` and `legacyDisableLayers: true` 
2. Codemod legacy css to bump specificity when needed
3. Rollout with `legacyDisableLayers: false` (add selector hack for CSS ordering)
4. (stretch) Rollout with `useLegacyClassnamesSort: false` for size win (nice to have)
The stylesheets with these legacy configs should be identical to what we have internally.
=> [babel-plugin][legacy] add legacyClassnamesSort config in `processStylexRules`

packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-shorthands-test.js, packages/@stylexjs/eslint-plugin/src/utils/splitShorthands.js
Fixes the `valid-shorthands` ESLint rule incorrectly flagging modern CSS color functions like `oklch()`, `oklab()`, `lch()`, etc. as invalid shorthand usage.
The `css-shorthand-expand` library used by the ESLint rule doesn't recognize modern CSS color functions, causing the rule to:
1. Incorrectly report these as invalid shorthands
2. Provide broken auto-fixes that split the color function by spaces
- **Detection**: Added preprocessing to detect modern CSS color functions (`oklch`, `oklab`, `lch`, `lab`, `color`, `hwb`)
- **Handling**: Treat these functions as single values that shouldn't be expanded by `css-shorthand-expand`  
- **Testing**: Added comprehensive test cases for all supported modern color functions
- **`splitShorthands.js`**: Added `containsModernColorFunction()` check and …
=> [eslint-plugin] Fix `valid-shorthands` rule for modern CSS color functions

examples/example-nextjs/app/Counter.tsx, examples/example-nextjs/app/globalTokens.stylex.ts, examples/example-nextjs/components/Card.tsx, examples/example-nextjs/next.config.js, examples/example-nextjs/package.json, examples/example-nextjs/postcss.config.js, package-lock.json
The @stylexjs/open-props package was deprecated in StyleX v0.12.0. While working with the Next.js example, I noticed it was still using this deprecated dependency, which could mislead developers following the example. 
For now, I’ve replaced the dependency by defining only the required color tokens locally. Would you recommend sticking with this approach, or should we migrate from `@stylexjs/open-props` to `@stylextras/open-props` as suggested in the [v0.12.0 release notes](https://stylexjs.com/blog/v0.12.0/#deprecations)?
Fixes #996 
There is no visual change in the example app preview:
=> chore: remove deprecated open-props package from nextjs example.

packages/@stylexjs/babel-plugin/src/index.d.ts
Some Flow-specific syntax seems to have sneaked into `0.16.1`'s `packages/@stylexjs/babel-plugin/src/index.d.ts`. 
Also TS objects are inexact by default, so the semantics are correct without the `...`.
=> [babel-plugin] Fix `index.d.ts`
